/// JumpList artifact models for EZ Tools JLECmd JSON output
use serde::{Deserialize, Serialize};

/// JLECmd Automatic Destinations JSON output entry
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct JumpListEntry {
    #[serde(alias = "SourceFile")]
    pub source_file: Option<String>,
    #[serde(alias = "AppId")]
    pub app_id: Option<String>,
    #[serde(alias = "AppIdDescription")]
    pub app_id_description: Option<String>,
    #[serde(alias = "DestListVersion")]
    pub dest_list_version: Option<i32>,
    #[serde(alias = "LastUsedEntryNumber")]
    pub last_used_entry_number: Option<i32>,
    #[serde(alias = "EntryNumber")]
    pub entry_number: Option<i32>,
    #[serde(alias = "CreationTime")]
    pub creation_time: Option<String>,
    #[serde(alias = "LastModified")]
    pub last_modified: Option<String>,
    #[serde(alias = "Hostname")]
    pub hostname: Option<String>,
    #[serde(alias = "MacAddress")]
    pub mac_address: Option<String>,
    #[serde(alias = "Path")]
    pub path: Option<String>,
    #[serde(alias = "PinStatus")]
    pub pin_status: Option<String>,
    #[serde(alias = "FileBirthDossier")]
    pub file_birth_dossier: Option<String>,
    #[serde(alias = "InteractionCount")]
    pub interaction_count: Option<i32>,
    #[serde(alias = "TargetCreated")]
    pub target_created: Option<String>,
    #[serde(alias = "TargetModified")]
    pub target_modified: Option<String>,
    #[serde(alias = "TargetAccessed")]
    pub target_accessed: Option<String>,
    #[serde(alias = "FileSize")]
    pub file_size: Option<i64>,
    #[serde(alias = "RelativePath")]
    pub relative_path: Option<String>,
    #[serde(alias = "WorkingDirectory")]
    pub working_directory: Option<String>,
    #[serde(alias = "FileAttributes")]
    pub file_attributes: Option<String>,
    #[serde(alias = "HeaderFlags")]
    pub header_flags: Option<String>,
    #[serde(alias = "DriveType")]
    pub drive_type: Option<String>,
    #[serde(alias = "DriveSerialNumber")]
    pub drive_serial_number: Option<String>,
    #[serde(alias = "VolumeLabel")]
    pub volume_label: Option<String>,
    #[serde(alias = "LocalPath")]
    pub local_path: Option<String>,
    #[serde(alias = "NetworkPath")]
    pub network_path: Option<String>,
    #[serde(alias = "CommonPath")]
    pub common_path: Option<String>,
    #[serde(alias = "TargetIDAbsolutePath")]
    pub target_id_absolute_path: Option<String>,
    #[serde(alias = "Arguments")]
    pub arguments: Option<String>,
    #[serde(alias = "MachineID")]
    pub machine_id: Option<String>,
    #[serde(alias = "MachineMACAddress")]
    pub machine_mac_address: Option<String>,
}
