//! Report Generation
//!
//! Generates reports in various formats (JSON, Markdown, HTML).

use crate::models::{AnalysisReport, Finding, PrefetchEntry, Severity};
use anyhow::Result;
use std::fs;
use std::path::Path;

/// Generate a JSON report
pub fn generate_json_report(report: &AnalysisReport) -> Result<String> {
    Ok(serde_json::to_string_pretty(report)?)
}

/// Generate a Markdown report
pub fn generate_markdown_report(report: &AnalysisReport) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# 🔍 Windows Prefetch Analysis Report\n\n");
    md.push_str(&format!("**Generated:** {}\n\n", report.generated_at.format("%Y-%m-%d %H:%M:%S UTC")));

    // Summary Section
    md.push_str("## 📊 Executive Summary\n\n");
    md.push_str("| Metric | Value |\n");
    md.push_str("|--------|-------|\n");
    md.push_str(&format!("| Total Prefetch Entries | {} |\n", report.total_entries));
    md.push_str(&format!("| Unique Executables | {} |\n", report.unique_executables));
    
    if let Some((start, end)) = report.date_range {
        md.push_str(&format!("| Date Range | {} to {} |\n", 
            start.format("%Y-%m-%d %H:%M"),
            end.format("%Y-%m-%d %H:%M")));
    }
    md.push_str(&format!("| Total Findings | {} |\n\n", report.summary.total()));

    // Severity Breakdown
    md.push_str("### Findings by Severity\n\n");
    md.push_str(&format!("- 🔴 **Critical:** {}\n", report.summary.critical));
    md.push_str(&format!("- 🟠 **High:** {}\n", report.summary.high));
    md.push_str(&format!("- 🟡 **Medium:** {}\n", report.summary.medium));
    md.push_str(&format!("- 🔵 **Low:** {}\n", report.summary.low));
    md.push_str(&format!("- ℹ️ **Info:** {}\n\n", report.summary.info));

    // Critical and High Findings
    let critical_high: Vec<_> = report.findings.iter()
        .filter(|f| f.severity >= Severity::High)
        .collect();

    if !critical_high.is_empty() {
        md.push_str("## 🚨 Critical & High Severity Findings\n\n");
        for finding in critical_high {
            md.push_str(&format_finding_md(finding));
        }
    }

    // All Findings Table
    md.push_str("## 📋 All Findings\n\n");
    md.push_str("| Severity | Executable | Category | Description | MITRE ATT&CK |\n");
    md.push_str("|----------|------------|----------|-------------|---------------|\n");

    for finding in &report.findings {
        let mitre = finding.mitre_attack.as_deref().unwrap_or("-");
        md.push_str(&format!(
            "| {} {} | `{}` | {} | {} | {} |\n",
            finding.severity.emoji(),
            finding.severity,
            finding.executable,
            finding.category,
            truncate(&finding.description, 50),
            mitre
        ));
    }

    // MITRE ATT&CK Mapping
    let mitre_findings: Vec<_> = report.findings.iter()
        .filter(|f| f.mitre_attack.is_some())
        .collect();

    if !mitre_findings.is_empty() {
        md.push_str("\n## 🎯 MITRE ATT&CK Mapping\n\n");
        md.push_str("| Technique ID | Technique Name | Executable | Description |\n");
        md.push_str("|--------------|----------------|------------|-------------|\n");

        for finding in mitre_findings {
            md.push_str(&format!(
                "| {} | {} | `{}` | {} |\n",
                finding.mitre_attack.as_deref().unwrap_or("-"),
                finding.mitre_name.as_deref().unwrap_or("-"),
                finding.executable,
                truncate(&finding.description, 40)
            ));
        }
    }

    // Timeline Section
    md.push_str("\n## ⏱️ Execution Timeline\n\n");
    md.push_str("Executables with the most recent activity:\n\n");
    
    let mut recent: Vec<_> = report.findings.iter()
        .filter(|f| f.last_run.is_some())
        .collect();
    recent.sort_by(|a, b| b.last_run.cmp(&a.last_run));
    recent.truncate(20);

    if !recent.is_empty() {
        md.push_str("| Last Run | Executable | Run Count | Severity |\n");
        md.push_str("|----------|------------|-----------|----------|\n");
        for finding in recent {
            if let Some(last) = finding.last_run {
                md.push_str(&format!(
                    "| {} | `{}` | {} | {} |\n",
                    last.format("%Y-%m-%d %H:%M:%S"),
                    finding.executable,
                    finding.run_count,
                    finding.severity
                ));
            }
        }
    }

    md.push_str("\n---\n");
    md.push_str("*Generated by Windows Prefetch Analyzer*\n");

    md
}

/// Format a single finding for markdown detail view
fn format_finding_md(finding: &Finding) -> String {
    let mut md = String::new();

    md.push_str(&format!("### {} {} - `{}`\n\n", 
        finding.severity.emoji(),
        finding.severity,
        finding.executable
    ));

    md.push_str(&format!("**Category:** {}\n\n", finding.category));
    md.push_str(&format!("**Description:** {}\n\n", finding.description));

    if let Some(ref mitre) = finding.mitre_attack {
        md.push_str(&format!("**MITRE ATT&CK:** {} - {}\n\n", 
            mitre,
            finding.mitre_name.as_deref().unwrap_or("Unknown")
        ));
    }

    if let Some(ref path) = finding.path {
        md.push_str(&format!("**Path:** `{}`\n\n", path));
    }

    if let Some(last) = finding.last_run {
        md.push_str(&format!("**Last Execution:** {} (Run Count: {})\n\n", 
            last.format("%Y-%m-%d %H:%M:%S"),
            finding.run_count
        ));
    }

    if let Some(ref context) = finding.context {
        md.push_str(&format!("**Context:** {}\n\n", context));
    }

    md.push_str("---\n\n");
    md
}

/// Generate HTML report with styled output (KaliHeker theme)
pub fn generate_html_report(report: &AnalysisReport) -> String {
    let mut html = String::new();

    html.push_str(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KaliHeker - Prefetch Analysis Report</title>
    <style>
        :root {
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --bg-tertiary: #1f2428;
            --border-color: #30363d;
            --text-primary: #c9d1d9;
            --text-secondary: #8b949e;
            --accent: #238636;
            --accent-light: #2ea043;
            --alert-bg: #da3633;
            --alert-text: #ffebe9;
            --warning-bg: #9e6a03;
            --warning-text: #fff8c5;
            --notice-bg: #238636;
            --notice-text: #f0f6fc;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            line-height: 1.5;
            min-height: 100vh;
        }
        header {
            background: var(--bg-secondary);
            border-bottom: 1px solid var(--border-color);
            padding: 24px;
        }
        .header-content { max-width: 1400px; margin: 0 auto; }
        .logo { display: flex; align-items: center; gap: 16px; margin-bottom: 20px; }
        .logo-text { font-size: 28px; font-weight: 700; color: var(--text-primary); letter-spacing: -0.5px; }
        .logo-text span { color: var(--accent-light); }
        .version { font-size: 14px; color: var(--text-secondary); background: var(--bg-tertiary); padding: 2px 8px; border-radius: 12px; border: 1px solid var(--border-color); }
        .scan-info { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; margin-top: 16px; }
        .info-card { background: var(--bg-tertiary); border: 1px solid var(--border-color); border-radius: 6px; padding: 12px 16px; }
        .info-card h3 { font-size: 12px; text-transform: uppercase; color: var(--text-secondary); margin-bottom: 4px; letter-spacing: 0.5px; }
        .info-card p { font-size: 14px; color: var(--text-primary); word-break: break-all; }
        .score { font-size: 18px; font-weight: 700; color: var(--text-primary); }
        nav {
            background: var(--bg-secondary);
            border-bottom: 1px solid var(--border-color);
            padding: 12px 24px;
            position: sticky;
            top: 0;
            z-index: 100;
            box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        }
        .nav-content { max-width: 1400px; margin: 0 auto; display: flex; flex-wrap: wrap; gap: 16px; align-items: center; justify-content: space-between; }
        .filter-buttons { display: flex; gap: 8px; flex-wrap: wrap; }
        .filter-btn {
            padding: 6px 14px; border: 1px solid var(--border-color); border-radius: 20px;
            background: var(--bg-tertiary); color: var(--text-primary); cursor: pointer; font-size: 13px; transition: all 0.2s;
        }
        .filter-btn:hover { border-color: var(--accent); }
        .filter-btn.active { background: var(--accent); color: #fff; border-color: var(--accent); }
        .filter-btn .count { margin-left: 6px; opacity: 0.8; font-size: 0.9em; }
        .search-box { display: flex; align-items: center; gap: 8px; }
        .search-box input {
            padding: 8px 14px; border: 1px solid var(--border-color); border-radius: 6px;
            background: var(--bg-tertiary); color: var(--text-primary); font-size: 14px; width: 280px;
        }
        .search-box input:focus { outline: none; border-color: var(--accent); box-shadow: 0 0 0 2px rgba(46, 160, 67, 0.4); }
        main { max-width: 1400px; margin: 0 auto; padding: 24px; }
        .stats-bar {
            display: flex; gap: 24px; margin-bottom: 20px; padding: 16px;
            background: var(--bg-secondary); border-radius: 8px; border: 1px solid var(--border-color);
        }
        .stat { display: flex; align-items: center; gap: 8px; }
        .stat-dot { width: 12px; height: 12px; border-radius: 50%; }
        .stat-dot.alert { background: var(--alert-bg); }
        .stat-dot.warning { background: var(--warning-bg); }
        .stat-dot.notice { background: var(--notice-bg); }
        .stat-label { font-size: 14px; color: var(--text-secondary); }
        .stat-value { font-size: 18px; font-weight: 600; }
        .finding-card {
            background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 8px; overflow: hidden;
            margin-bottom: 16px; transition: transform 0.2s; border-left: 4px solid var(--border-color);
        }
        .finding-card:hover { transform: translateY(-2px); border-color: var(--accent); }
        .finding-card.critical { border-left-color: var(--alert-bg); }
        .finding-card.high { border-left-color: #fd8c00; }
        .finding-card.medium { border-left-color: var(--warning-bg); }
        .finding-card.low { border-left-color: var(--notice-bg); }
        .finding-card.info { border-left-color: #1f6feb; }
        .finding-header {
            display: flex; align-items: center; gap: 12px; padding: 16px;
            background: var(--bg-tertiary); border-bottom: 1px solid var(--border-color); flex-wrap: wrap;
        }
        .severity-badge { padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }
        .severity-badge.critical { background: var(--alert-bg); color: var(--alert-text); }
        .severity-badge.high { background: #fd8c00; color: #fff; }
        .severity-badge.medium { background: var(--warning-bg); color: var(--warning-text); }
        .severity-badge.low { background: var(--notice-bg); color: var(--notice-text); }
        .severity-badge.info { background: #1f6feb; color: #fff; }
        .finding-title {
            flex: 1; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 14px; font-weight: 600;
            color: var(--accent-light); word-break: break-all;
        }
        .finding-body { padding: 16px; }
        .finding-description { margin-bottom: 16px; color: var(--text-primary); font-size: 14px; }
        .evidence-box {
            background: var(--bg-primary); border: 1px solid var(--border-color); border-radius: 6px; padding: 12px;
            margin-bottom: 12px; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 12px; overflow-x: auto;
        }
        .evidence-line { margin-bottom: 4px; }
        .evidence-label { color: var(--text-secondary); margin-right: 8px; }
        .metadata-tags { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 12px; }
        .meta-tag {
            background: var(--bg-tertiary); border: 1px solid var(--border-color); border-radius: 12px;
            padding: 2px 10px; font-size: 11px; color: var(--text-secondary);
        }
        .meta-tag strong { color: var(--text-primary); }
        .mitre-link { color: var(--accent-light); text-decoration: none; }
        .mitre-link:hover { text-decoration: underline; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid var(--border-color); }
        th { background: var(--bg-tertiary); color: var(--accent-light); font-size: 12px; text-transform: uppercase; }
        tr:hover { background: rgba(255,255,255,0.03); }
        code {
            background: var(--bg-primary); padding: 2px 6px; border-radius: 4px;
            font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace; font-size: 13px;
        }
        footer {
            text-align: center; padding: 40px 20px; color: var(--text-secondary); font-size: 13px;
            border-top: 1px solid var(--border-color); margin-top: 40px;
        }
        .category-header {
            display: flex; align-items: center; gap: 12px; padding: 16px 20px;
            background: var(--bg-secondary); border: 1px solid var(--border-color);
            border-radius: 8px; margin-bottom: 16px; border-left: 4px solid var(--accent);
        }
        .category-header h3 { flex: 1; font-size: 16px; font-weight: 600; color: var(--text-primary); margin: 0; }
        .category-count { color: var(--text-secondary); font-size: 13px; background: var(--bg-tertiary); padding: 4px 10px; border-radius: 12px; }
        .icon {
            width: 14px; height: 14px; border-radius: 50%; display: inline-block;
            background: radial-gradient(circle at 30% 30%, rgba(255,255,255,0.35), var(--accent-light));
            box-shadow: 0 0 8px rgba(46, 160, 67, 0.4);
        }
        /* ── New sections ── */
        .benign-note {
            background: #0d2b0d; border: 1px solid #238636; border-radius: 6px;
            padding: 10px 14px; margin-bottom: 12px; font-size: 13px; color: #56d364;
        }
        .benign-note strong { color: #3fb950; }
        .loaded-files-box {
            background: var(--bg-primary); border: 1px solid #30363d; border-radius: 6px;
            padding: 10px 14px; margin-bottom: 12px; font-size: 12px;
        }
        .loaded-files-box summary {
            cursor: pointer; color: var(--text-secondary); font-size: 12px;
            padding: 2px 0; user-select: none;
        }
        .loaded-files-box summary:hover { color: var(--accent-light); }
        .loaded-files-list { margin-top: 8px; }
        .loaded-files-list li {
            font-family: 'SF Mono','Fira Code',monospace;
            color: var(--text-primary); padding: 2px 0;
            word-break: break-all; list-style: none;
        }
        .loaded-files-list li::before { content: "→ "; color: var(--text-secondary); }
        #entry-table td, #entry-table th { font-size: 12px; }
        .section-nav { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 24px; }
        .section-nav a {
            padding: 6px 14px; background: var(--bg-tertiary); border: 1px solid var(--border-color);
            border-radius: 20px; color: var(--text-secondary); text-decoration: none; font-size: 13px;
        }
        .section-nav a:hover { border-color: var(--accent); color: var(--accent-light); }
        /* ── Chart section ── */
        .charts-outer { margin-bottom: 32px; }
        .charts-row-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
        @media (max-width: 900px) { .charts-row-2 { grid-template-columns: 1fr; } }
        .chart-card {
            background: var(--bg-secondary); border: 1px solid var(--border-color);
            border-radius: 8px; padding: 16px; margin-bottom: 16px; position: relative;
        }
        .chart-title { font-size: 14px; font-weight: 600; color: var(--text-primary); margin-bottom: 4px; }
        .chart-sub { font-size: 12px; color: var(--text-secondary); margin-bottom: 12px; }
        .chart-canvas { display: block; width: 100%; cursor: crosshair; }
        .chart-tooltip {
            display: none; position: absolute; z-index: 999;
            background: #1f2428ee; border: 1px solid var(--border-color);
            border-radius: 6px; padding: 8px 12px; font-size: 12px;
            color: var(--text-primary); max-width: 320px;
            pointer-events: none; white-space: normal; line-height: 1.5;
        }
        .chart-tooltip hr { border-color: var(--border-color); margin: 4px 0; }
        .chart-tooltip code { font-size: 11px; }
        .dll-radial-wrap { display: flex; flex-wrap: wrap; gap: 16px; justify-content: center; }
        .dll-svg-wrap { display: flex; flex-direction: column; align-items: center; gap: 6px; }
        .dll-title { font-size: 12px; font-weight: 600; font-family: monospace; }
    </style>
</head>
<body>
    <header>
        <div class="header-content">
            <div class="logo">
                <div class="logo-text">KALI<span>HEKER</span></div>
                <div class="version">Prefetch Analyzer v1.0</div>
            </div>
            <div class="scan-info">
"#);

    // Info cards
    html.push_str(&format!(r#"
                <div class="info-card"><h3>Report Generated</h3><p>{}</p></div>
                <div class="info-card"><h3>Prefetch Entries</h3><div class="score">{}</div></div>
                <div class="info-card"><h3>Unique Executables</h3><div class="score">{}</div></div>
                <div class="info-card"><h3>Total Findings</h3><p>Critical: {} | High: {} | Medium: {} | Low: {}</p></div>
"#, 
        report.generated_at.format("%Y-%m-%d %H:%M:%S UTC"),
        report.total_entries,
        report.unique_executables,
        report.summary.critical,
        report.summary.high,
        report.summary.medium,
        report.summary.low
    ));

    html.push_str(r#"
            </div>
        </div>
    </header>

    <nav>
        <div class="nav-content">
            <div class="filter-buttons">
"#);

    html.push_str(&format!(r#"
                <button class="filter-btn active">All <span class="count">({})</span></button>
                <button class="filter-btn">Critical <span class="count">({})</span></button>
                <button class="filter-btn">High <span class="count">({})</span></button>
                <button class="filter-btn">Medium <span class="count">({})</span></button>
"#, 
        report.summary.total(),
        report.summary.critical,
        report.summary.high,
        report.summary.medium
    ));

    html.push_str(r#"
            </div>
            <div class="search-box">
                <input type="text" id="searchInput" placeholder="Search findings...">
            </div>
        </div>
    </nav>

    <main>
        <div class="stats-bar">
"#);

    html.push_str(&format!(r#"
            <div class="stat"><div class="stat-dot alert"></div> <span class="stat-label">Critical:</span> <span class="stat-value">{}</span></div>
            <div class="stat"><div class="stat-dot warning"></div> <span class="stat-label">High/Med:</span> <span class="stat-value">{}</span></div>
            <div class="stat"><div class="stat-dot notice"></div> <span class="stat-label">Low/Info:</span> <span class="stat-value">{}</span></div>
"#, 
        report.summary.critical,
        report.summary.high + report.summary.medium,
        report.summary.low + report.summary.info
    ));

    html.push_str(r##"
        </div>
        <div class="section-nav">
            <a href="#section-charts">📊 Analytics</a>
            <a href="#section-findings">🚨 Findings</a>
            <a href="#section-all-findings">📋 All Findings</a>
            <a href="#section-entry-table">🗂️ Prefetch Entries</a>
            <a href="#section-timestamps">⏱️ Timestamps</a>
            <a href="#section-timeline">📅 Timeline</a>
        </div>
"##);

    // ── Visual Analytics Charts ────────────────────────────────────────────
    html.push_str(&generate_charts_html(&report.raw_entries, &report.findings));

    // Critical & High Findings
    let critical_high: Vec<_> = report.findings.iter()
        .filter(|f| f.severity >= Severity::High)
        .collect();

    if !critical_high.is_empty() {
        html.push_str(r##"
        <div class="category-header" id="section-findings" style="border-left-color: var(--alert-bg);">
            <span class="icon"></span>
            <h3>🚨 Critical &amp; High Severity Findings</h3>
            <span class="category-count">"##);
        html.push_str(&format!("{} findings", critical_high.len()));
        html.push_str(r#"</span>
        </div>
"#);
        
        for finding in &critical_high {
            let severity_class = match finding.severity {
                Severity::Critical => "critical",
                Severity::High => "high",
                _ => "medium",
            };
            
            html.push_str(&format!(r#"
        <div class="finding-card {}">
            <div class="finding-header">
                <span class="severity-badge {}">{}</span>
                <span class="finding-title">{}</span>
            </div>
            <div class="finding-body">
                <div class="finding-description">{}</div>
"#, 
                severity_class,
                severity_class,
                finding.severity,
                finding.executable,
                finding.description
            ));
            
            // Benign installer annotation
            if finding.likely_benign_installer {
                html.push_str(r#"
                <div class="benign-note">
                    <strong>⚠️ Likely Benign — Installer Pattern Detected</strong><br>
                    This path matches the standard Microsoft Visual C++ Redistributable (VCREDIST / VC_REDIST)
                    self-extraction staging pattern: <code>\WINDOWS\TEMP\{GUID}\.CR\</code> or <code>\.BE\</code>.
                    These sub-directories are created transiently by the installer bootstrapper during package
                    staging and are almost certainly not an independent threat. Verify that the parent installer
                    was authorised before escalating.
                </div>
"#);
            }

            // Context / explanation block
            if let Some(ref ctx) = finding.context {
                html.push_str(&format!(r#"
                <div class="evidence-box" style="border-left: 3px solid #8b949e; margin-bottom:12px;">
                    <div class="evidence-line" style="color:var(--text-secondary);font-size:11px;margin-bottom:4px;">ANALYST CONTEXT</div>
                    <div style="font-family:inherit;font-size:13px;color:var(--text-primary);white-space:pre-wrap;word-break:break-word;">{}</div>
                </div>
"#, html_escape(ctx)));
            }

            // Evidence box with path
            if let Some(ref path) = finding.path {
                html.push_str(&format!(r#"
                <div class="evidence-box">
                    <div class="evidence-line"><span class="evidence-label">[full path]</span> {}</div>
                </div>
"#, html_escape(path)));
            }

            // Loaded files / DLLs evidence
            if !finding.loaded_files.is_empty() {
                html.push_str(&format!(r#"
                <div class="loaded-files-box">
                    <details>
                        <summary>📂 Non-system loaded files / DLLs ({} shown)</summary>
                        <ul class="loaded-files-list">
"#, finding.loaded_files.len()));
                for f in &finding.loaded_files {
                    html.push_str(&format!("                            <li>{}</li>\n", html_escape(f)));
                }
                html.push_str(r#"
                        </ul>
                    </details>
                </div>
"#);
            }
            
            // Metadata tags
            html.push_str(r#"<div class="metadata-tags">"#);
            html.push_str(&format!(r#"<div class="meta-tag">Category: <strong>{}</strong></div>"#, finding.category));
            
            if let Some(ref mitre) = finding.mitre_attack {
                html.push_str(&format!(
                    r#"<div class="meta-tag">MITRE: <a class="mitre-link" href="https://attack.mitre.org/techniques/{}" target="_blank"><strong>{}</strong></a></div>"#,
                    mitre.replace('.', "/"),
                    mitre
                ));
            }
            
            if finding.run_count > 0 {
                html.push_str(&format!(r#"<div class="meta-tag">Run Count: <strong>{}</strong></div>"#, finding.run_count));
            }
            
            html.push_str(r#"</div>
            </div>
        </div>
"#);
        }
    }

    // ── Findings with Analyst Context (Medium / Low with context, benign notes, loaded files) ──
    let notable_with_context: Vec<_> = report.findings.iter()
        .filter(|f| f.severity < Severity::High)
        .filter(|f| f.context.is_some() || !f.loaded_files.is_empty() || f.likely_benign_installer)
        .collect();

    if !notable_with_context.is_empty() {
        html.push_str(r#"
        <div class="category-header" style="border-left-color: #d29922;">
            <span class="icon"></span>
            <h3>🔎 Analyst Context — Medium / Low Findings</h3>
            <span class="category-count">"#);
        html.push_str(&format!("{} findings with context", notable_with_context.len()));
        html.push_str(r#"</span>
        </div>
"#);

        for finding in &notable_with_context {
            let severity_class = match finding.severity {
                Severity::Medium => "medium",
                Severity::Low => "low",
                _ => "info",
            };

            html.push_str(&format!(r#"
        <div class="finding-card {}">
            <div class="finding-header">
                <span class="severity-badge {}">{}</span>
                <span class="finding-title">{}</span>
            </div>
            <div class="finding-body">
                <div class="finding-description">{}</div>
"#,
                severity_class,
                severity_class,
                finding.severity,
                html_escape(&finding.executable),
                html_escape(&finding.description)
            ));

            // Benign installer annotation
            if finding.likely_benign_installer {
                html.push_str(r#"
                <div class="benign-note">
                    <strong>⚠️ Likely Benign — Installer Pattern Detected</strong><br>
                    This path matches the standard Microsoft Visual C++ Redistributable (VCREDIST / VC_REDIST)
                    self-extraction staging pattern: <code>\WINDOWS\TEMP\{GUID}\.CR\</code> or <code>\.BE\</code>.
                    These sub-directories are created transiently by the installer bootstrapper during package
                    staging and are almost certainly not an independent threat. Verify that the parent installer
                    was authorised before escalating.
                </div>
"#);
            }

            // Context / explanation block
            if let Some(ref ctx) = finding.context {
                html.push_str(&format!(r#"
                <div class="evidence-box" style="border-left: 3px solid #8b949e; margin-bottom:12px;">
                    <div class="evidence-line" style="color:var(--text-secondary);font-size:11px;margin-bottom:4px;">ANALYST CONTEXT</div>
                    <div style="font-family:inherit;font-size:13px;color:var(--text-primary);white-space:pre-wrap;word-break:break-word;">{}</div>
                </div>
"#, html_escape(ctx)));
            }

            // Evidence box with path
            if let Some(ref path) = finding.path {
                html.push_str(&format!(r#"
                <div class="evidence-box">
                    <div class="evidence-line"><span class="evidence-label">[full path]</span> {}</div>
                </div>
"#, html_escape(path)));
            }

            // Loaded files / DLLs evidence
            if !finding.loaded_files.is_empty() {
                html.push_str(&format!(r#"
                <div class="loaded-files-box">
                    <details>
                        <summary>📂 Non-system loaded files / DLLs ({} shown)</summary>
                        <ul class="loaded-files-list">
"#, finding.loaded_files.len()));
                for f in &finding.loaded_files {
                    html.push_str(&format!("                            <li>{}</li>\n", html_escape(f)));
                }
                html.push_str(r#"
                        </ul>
                    </details>
                </div>
"#);
            }

            // Metadata tags
            html.push_str(r#"<div class="metadata-tags">"#);
            html.push_str(&format!(r#"<div class="meta-tag">Category: <strong>{}</strong></div>"#,
                html_escape(&finding.category.to_string())));
            if let Some(ref mitre) = finding.mitre_attack {
                html.push_str(&format!(
                    r#"<div class="meta-tag">MITRE: <a class="mitre-link" href="https://attack.mitre.org/techniques/{}" target="_blank"><strong>{}</strong></a></div>"#,
                    mitre.replace('.', "/"), mitre));
            }
            if finding.run_count > 0 {
                html.push_str(&format!(r#"<div class="meta-tag">Run Count: <strong>{}</strong></div>"#, finding.run_count));
            }
            html.push_str(r#"</div>
            </div>
        </div>
"#);
        }
    }

    // All Findings Table
    html.push_str(r##"
        <div class="category-header" id="section-all-findings">
            <span class="icon"></span>
            <h3>📋 All Findings</h3>
            <span class="category-count">"##);
    html.push_str(&format!("{} total", report.findings.len()));
    html.push_str(r#"</span>
        </div>
        
        <div style="background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 8px; overflow: hidden;">
            <table>
                <thead>
                    <tr>
                        <th>Severity</th>
                        <th>Executable</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>MITRE ATT&CK</th>
                    </tr>
                </thead>
                <tbody>
"#);

    for finding in &report.findings {
        let severity_class = match finding.severity {
            Severity::Critical => "critical",
            Severity::High => "high",
            Severity::Medium => "medium",
            Severity::Low => "low",
            Severity::Info => "info",
        };
        
        html.push_str(&format!(r#"
                    <tr>
                        <td><span class="severity-badge {}">{}</span></td>
                        <td><code>{}</code></td>
                        <td>{}</td>
                        <td>{}</td>
                        <td>{}</td>
                    </tr>
"#,
            severity_class,
            finding.severity,
            finding.executable,
            finding.category,
            truncate(&finding.description, 60),
            finding.mitre_attack.as_ref().map(|m| 
                format!(r#"<a class="mitre-link" href="https://attack.mitre.org/techniques/{}" target="_blank">{}</a>"#, 
                    m.replace('.', "/"), m)
            ).unwrap_or_else(|| "-".to_string())
        ));
    }

    html.push_str(r#"
                </tbody>
            </table>
        </div>
"#);

    // ── New enriched sections ──────────────────────────────────────────────
    html.push_str(&generate_complete_entry_table_html(&report.raw_entries));
    html.push_str(&generate_timestamps_html(&report.raw_entries));
    html.push_str(&generate_timeline_html(&report.raw_entries));

    // Footer and JavaScript
    html.push_str(r#"
    </main>
    
    <footer>
        <p>Generated by <strong>KaliHeker Prefetch Analyzer</strong></p>
        <p>A forensic analysis tool for Windows Prefetch data</p>
    </footer>

    <script>
        // Filter functionality
        let currentFilter = 'all';
        
        document.querySelectorAll('.filter-btn').forEach(btn => {
            btn.addEventListener('click', function() {
                // Update active state
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                this.classList.add('active');
                
                // Get filter type from button text
                const filterText = this.textContent.trim().toLowerCase();
                if (filterText.startsWith('all')) currentFilter = 'all';
                else if (filterText.startsWith('critical')) currentFilter = 'critical';
                else if (filterText.startsWith('high')) currentFilter = 'high';
                else if (filterText.startsWith('medium')) currentFilter = 'medium';
                else if (filterText.startsWith('low')) currentFilter = 'low';
                
                applyFilters();
            });
        });
        
        function applyFilters() {
            // Filter finding cards
            document.querySelectorAll('.finding-card').forEach(card => {
                const level = card.classList.contains('critical') ? 'critical' :
                             card.classList.contains('high') ? 'high' :
                             card.classList.contains('medium') ? 'medium' :
                             card.classList.contains('low') ? 'low' : 'info';
                
                if (currentFilter === 'all' || level === currentFilter) {
                    card.style.display = '';
                } else {
                    card.style.display = 'none';
                }
            });
            
            // Filter table rows
            document.querySelectorAll('tbody tr').forEach(row => {
                const badge = row.querySelector('.severity-badge');
                if (!badge) return;
                
                const level = badge.classList.contains('critical') ? 'critical' :
                             badge.classList.contains('high') ? 'high' :
                             badge.classList.contains('medium') ? 'medium' :
                             badge.classList.contains('low') ? 'low' : 'info';
                
                if (currentFilter === 'all' || level === currentFilter) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
            
            updateVisibleCount();
        }
        
        function updateVisibleCount() {
            const visibleCards = document.querySelectorAll('.finding-card:not([style*="display: none"])').length;
            const visibleRows = document.querySelectorAll('tbody tr:not([style*="display: none"])').length;
            
            // Update category counts if elements exist
            const categoryHeaders = document.querySelectorAll('.category-header');
            categoryHeaders.forEach(header => {
                const countSpan = header.querySelector('.category-count');
                if (countSpan && header.querySelector('h3').textContent.includes('All Findings')) {
                    countSpan.textContent = visibleRows + ' visible';
                }
            });
        }
        
        // Search functionality (if search box exists)
        const searchInput = document.getElementById('searchInput');
        if (searchInput) {
            searchInput.addEventListener('input', function() {
                const query = this.value.toLowerCase();
                
                document.querySelectorAll('.finding-card').forEach(card => {
                    const text = card.textContent.toLowerCase();
                    if (text.includes(query)) {
                        card.style.display = '';
                    } else {
                        card.style.display = 'none';
                    }
                });
                
                document.querySelectorAll('tbody tr').forEach(row => {
                    const text = row.textContent.toLowerCase();
                    if (text.includes(query)) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        }
        
        // Collapsible sections
        document.querySelectorAll('.category-header').forEach(header => {
            header.style.cursor = 'pointer';
            header.addEventListener('click', function() {
                const nextSibling = this.nextElementSibling;
                if (nextSibling && (nextSibling.tagName === 'DIV' || nextSibling.classList.contains('finding-card'))) {
                    // Toggle visibility of all following finding cards until next header
                    let sibling = this.nextElementSibling;
                    while (sibling && !sibling.classList.contains('category-header')) {
                        if (sibling.style.display === 'none') {
                            sibling.style.display = '';
                        } else {
                            sibling.style.display = 'none';
                        }
                        sibling = sibling.nextElementSibling;
                    }
                }
            });
        });
    </script>
</body>
</html>
"#);

    html
}

/// Save report to file
pub fn save_report<P: AsRef<Path>>(path: P, content: &str) -> Result<()> {
    fs::write(path, content)?;
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
//  Visual Analytics Charts
// ─────────────────────────────────────────────────────────────────────────────

/// Build the full charts section: HTML containers + embedded JSON data +
/// pure-SVG/Canvas JavaScript renderers (no external dependencies).
pub fn generate_charts_html(entries: &[PrefetchEntry], findings: &[crate::models::Finding]) -> String {
    use std::collections::{HashMap, HashSet};
    use crate::models::{Severity, FindingCategory};

    // ── Severity helper ──────────────────────────────────────────────────
    let sev_num = |s: &Severity| -> u8 {
        match s {
            Severity::Critical => 5,
            Severity::High => 4,
            Severity::Medium => 3,
            Severity::Low => 2,
            Severity::Info => 1,
        }
    };

    // exe_name(upper) → max severity numeric across all findings
    let mut exe_sev: HashMap<String, u8> = HashMap::new();
    for f in findings {
        let n = sev_num(&f.severity);
        let e = exe_sev.entry(f.executable.to_uppercase()).or_insert(0);
        if n > *e { *e = n; }
    }

    // ── Chart 1: Run-Count Histogram ─────────────────────────────────────
    let (mut b1, mut b2, mut b6, mut b11): (Vec<serde_json::Value>, Vec<serde_json::Value>, Vec<serde_json::Value>, Vec<serde_json::Value>) =
        (vec![], vec![], vec![], vec![]);

    for entry in entries {
        let runs = entry.run_count().max(1);
        let sev = *exe_sev.get(&entry.executable_name.to_uppercase()).unwrap_or(&0);
        let v = serde_json::json!({"n": entry.executable_name, "r": runs, "s": sev});
        match runs {
            1 => b1.push(v),
            2..=5 => b2.push(v),
            6..=10 => b6.push(v),
            _ => b11.push(v),
        }
    }

    // ── Chart 2: Timeline events ─────────────────────────────────────────
    let mut timeline: Vec<serde_json::Value> = Vec::new();
    for entry in entries {
        let sev = *exe_sev.get(&entry.executable_name.to_uppercase()).unwrap_or(&0);
        let hash = entry.extract_prefetch_hash().unwrap_or_default();
        for ts in entry.get_run_times() {
            let ms = ts.and_utc().timestamp_millis();
            timeline.push(serde_json::json!({
                "t": ms,
                "ts": ts.format("%Y-%m-%d %H:%M:%S").to_string(),
                "e": &entry.executable_name,
                "s": sev,
                "h": &hash,
            }));
        }
    }
    timeline.sort_by_key(|v| v["t"].as_i64().unwrap_or(0));

    // ── Chart 3: Burst scatter (rolling 60-second unique-process window) ─
    let raw_events: Vec<(i64, &str)> = timeline.iter()
        .filter_map(|v| Some((v["t"].as_i64()?, v["e"].as_str()?)))
        .collect();

    let window_ms: i64 = 60_000;
    let mut burst: Vec<serde_json::Value> = Vec::new();
    for (i, &(t, _)) in raw_events.iter().enumerate() {
        let w_start = t - window_ms;
        let count = raw_events.iter()
            .filter(|(ts, _)| *ts >= w_start && *ts <= t)
            .map(|(_, e)| *e)
            .collect::<HashSet<_>>()
            .len();
        let ts_str = timeline[i]["ts"].as_str().unwrap_or("").to_string();
        burst.push(serde_json::json!({"t": t, "ts": ts_str, "c": count}));
    }

    // ── Chart 4: File-Path Treemap ────────────────────────────────────────
    let susp_patterns = [
        "\\TEMP\\", "\\PUBLIC\\", "\\DOWNLOADS\\", "\\APPDATA\\ROAMING\\",
        "$RECYCLE", "\\PERFLOGS\\", "\\DEBUG\\", "\\MUSIC\\", "\\VIDEOS\\", "\\PICTURES\\",
    ];

    let mut dir_map: HashMap<String, Vec<serde_json::Value>> = HashMap::new();
    for entry in entries {
        let exe_path = entry.get_executable_path()
            .unwrap_or_else(|| format!("\\UNKNOWN\\{}", &entry.executable_name));
        let up = exe_path.to_uppercase();

        // Strip volume prefix, keep directory portion
        let dir = if let Some(rb) = up.find('}') {
            let after = &up[rb + 1..];
            if let Some(sep) = after.rfind('\\') { after[..sep + 1].to_string() }
            else { after.to_string() }
        } else if let Some(sep) = up.rfind('\\') {
            up[..sep + 1].to_string()
        } else {
            "\\UNKNOWN\\".to_string()
        };

        let sev = *exe_sev.get(&entry.executable_name.to_uppercase()).unwrap_or(&0);
        let susp = susp_patterns.iter().any(|p| up.contains(p));
        let runs = entry.run_count().max(1) as u64;

        dir_map.entry(dir.clone()).or_default().push(serde_json::json!({
            "n": &entry.executable_name, "r": runs, "s": sev, "p": exe_path, "susp": susp
        }));
    }

    let mut treemap: Vec<serde_json::Value> = dir_map.into_iter().map(|(dir, children)| {
        let tot: u64 = children.iter().filter_map(|c| c["r"].as_u64()).sum();
        let max_s: u8 = children.iter().filter_map(|c| c["s"].as_u64().map(|v| v as u8)).max().unwrap_or(0);
        let susp = susp_patterns.iter().any(|p| dir.to_uppercase().contains(p));
        serde_json::json!({"n": dir, "r": tot, "s": max_s, "susp": susp, "c": children})
    }).collect();
    treemap.sort_by(|a, b| b["r"].as_u64().cmp(&a["r"].as_u64()));

    // ── Chart 5: DLL Radial graphs ────────────────────────────────────────
    let flagged_exes: HashSet<String> = findings.iter()
        .filter(|f| f.severity >= Severity::High
            || matches!(f.category, FindingCategory::SuspiciousDll))
        .map(|f| f.executable.to_uppercase())
        .collect();

    let susp_dll_paths: HashSet<String> = findings.iter()
        .filter(|f| matches!(f.category, FindingCategory::SuspiciousDll))
        .filter_map(|f| f.path.as_ref().map(|p| p.to_uppercase()))
        .collect();

    let sys_prefixes = ["\\WINDOWS\\SYSTEM32\\", "\\WINDOWS\\SYSWOW64\\",
                        "\\WINDOWS\\WINSXS\\", "\\WINDOWS\\MICROSOFT.NET\\"];

    let dll_graphs: Vec<serde_json::Value> = entries.iter()
        .filter(|e| flagged_exes.contains(&e.executable_name.to_uppercase()))
        .map(|entry| {
            let sev = *exe_sev.get(&entry.executable_name.to_uppercase()).unwrap_or(&0);
            let dlls: Vec<serde_json::Value> = entry.get_files().iter()
                .filter(|f| { let u = f.to_uppercase(); u.ends_with(".DLL") || u.ends_with(".SYS") })
                .take(60)
                .map(|f| {
                    let u = f.to_uppercase();
                    let is_sys = sys_prefixes.iter().any(|p| u.contains(p));
                    let is_susp = susp_dll_paths.iter().any(|p| u == *p);
                    let name = std::path::Path::new(f.as_str())
                        .file_name().and_then(|n| n.to_str()).unwrap_or(f.as_str()).to_string();
                    serde_json::json!({"n": name, "p": f, "sys": is_sys, "susp": is_susp})
                })
                .collect();
            serde_json::json!({"exe": &entry.executable_name, "sev": sev, "dlls": dlls})
        })
        .collect();

    // ── Serialize all chart data to JSON ─────────────────────────────────
    let chart_json = serde_json::to_string(&serde_json::json!({
        "hist": {"b1": b1, "b2": b2, "b6": b6, "b11": b11},
        "timeline": timeline,
        "burst": burst,
        "treemap": treemap,
        "dlls": dll_graphs,
    })).unwrap_or_default();

    // ── Assemble HTML ─────────────────────────────────────────────────────
    let mut html = String::new();

    // Section header
    html.push_str(r#"
        <div class="category-header" id="section-charts" style="border-left-color: #58a6ff;">
            <span class="icon"></span>
            <h3>📊 Visual Analytics</h3>
            <span class="category-count">5 interactive charts</span>
        </div>
        <div class="charts-outer">
"#);

    // Embed data as JSON
    html.push_str("<script>\nconst CHART_DATA = ");
    html.push_str(&chart_json);
    html.push_str(";\n</script>\n");

    // Chart containers
    html.push_str(r#"
        <!-- Row 1: Histogram + Burst -->
        <div class="charts-row-2">
            <div class="chart-card" id="c-hist">
                <div class="chart-title">Run Count Distribution</div>
                <div class="chart-sub">Executables bucketed by total run count — single-execution binaries (leftmost) are strongest indicators</div>
                <canvas id="canvas-hist" class="chart-canvas" height="280"></canvas>
                <div id="hist-tooltip" class="chart-tooltip"></div>
            </div>
            <div class="chart-card" id="c-burst">
                <div class="chart-title">Execution Burst Scatter</div>
                <div class="chart-sub">Unique processes in rolling 60-second window — spikes indicate scripted attack waves</div>
                <canvas id="canvas-burst" class="chart-canvas" height="280"></canvas>
                <div id="burst-tooltip" class="chart-tooltip"></div>
            </div>
        </div>

        <!-- Row 2: Execution Timeline (full width) -->
        <div class="chart-card" id="c-timeline">
            <div class="chart-title">Execution Timeline</div>
            <div class="chart-sub">Every execution event plotted in time — color-coded by severity · scroll horizontally · hover for details</div>
            <canvas id="canvas-timeline" class="chart-canvas" height="340"></canvas>
            <div id="timeline-tooltip" class="chart-tooltip"></div>
        </div>

        <!-- Row 3: File Path Treemap (full width) -->
        <div class="chart-card" id="c-treemap">
            <div class="chart-title">File Path Treemap</div>
            <div class="chart-sub">Execution directories sized by total run count — orange/red boxes indicate suspicious paths · hover for details</div>
            <canvas id="canvas-treemap" class="chart-canvas" height="420"></canvas>
            <div id="treemap-tooltip" class="chart-tooltip"></div>
        </div>

        <!-- Row 4: DLL Radial graphs -->
        <div class="chart-card" id="c-dll">
            <div class="chart-title">DLL Load Graph — Flagged Executables</div>
            <div class="chart-sub">Radial spoke layout · grey = system DLL · red = suspicious · yellow = non-system · hover node for full path</div>
            <div id="dll-radial-container" class="dll-radial-wrap"></div>
        </div>
        </div>
"#);

    // The chart rendering JavaScript (no format placeholders — pure static JS)
    html.push_str(r#"
<script>
(function() {
'use strict';

// ─── Palette ────────────────────────────────────────────────────────────────
const SEV_COLOR  = ['#58a6ff','#56d364','#d29922','#fd8c00','#da3633','#ff0062'];
const SEV_LABEL  = ['none','INFO','LOW','MEDIUM','HIGH','CRITICAL'];
const C = {
    bg:   '#0d1117', bg2: '#161b22', bg3: '#1f2428',
    bdr:  '#30363d', txt: '#c9d1d9', dim: '#8b949e',
    acc:  '#2ea043', red: '#da3633', ora: '#fd8c00',
    yel:  '#d29922', blu: '#58a6ff', grn: '#56d364',
    susp: '#fd8c00',
};

function sevColor(s) { return SEV_COLOR[Math.min(s, 5)] || C.blu; }
function px(v) { return Math.round(v); }

// ─── DPI-aware canvas setup ──────────────────────────────────────────────────
function setupCanvas(id) {
    const cv = document.getElementById(id);
    if (!cv) return null;
    const dpr = window.devicePixelRatio || 1;
    const card = cv.parentElement;
    const w    = card.clientWidth - 32;
    const h    = parseInt(cv.getAttribute('height')) || 280;
    cv.width  = w * dpr;
    cv.height = h * dpr;
    cv.style.width  = w + 'px';
    cv.style.height = h + 'px';
    const ctx = cv.getContext('2d');
    ctx.scale(dpr, dpr);
    return {cv, ctx, w, h, dpr};
}

// ─── Tooltip helper ─────────────────────────────────────────────────────────
function showTip(tipEl, cv, x, y, html) {
    const r = cv.getBoundingClientRect();
    tipEl.innerHTML = html;
    tipEl.style.display = 'block';
    tipEl.style.left = (x + 12) + 'px';
    tipEl.style.top  = (y + 12) + 'px';
}
function hideTip(tipEl) { tipEl.style.display = 'none'; }

// ─────────────────────────────────────────────────────────────────────────────
// CHART 1 — Run Count Histogram
// ─────────────────────────────────────────────────────────────────────────────
function renderHistogram() {
    const S = setupCanvas('canvas-hist');
    if (!S) return;
    const {cv, ctx, w, h} = S;
    const tip = document.getElementById('hist-tooltip');

    const buckets = [
        { label:'1× (Single)', key:'b1', items: CHART_DATA.hist.b1 },
        { label:'2–5×',        key:'b2', items: CHART_DATA.hist.b2 },
        { label:'6–10×',       key:'b6', items: CHART_DATA.hist.b6 },
        { label:'11× +',       key:'b11',items: CHART_DATA.hist.b11 },
    ];

    const PAD = {t:20, r:20, b:52, l:50};
    const cw = w - PAD.l - PAD.r;
    const ch = h - PAD.t - PAD.b;
    const maxLen = Math.max(...buckets.map(b => b.items.length), 1);

    // Background
    ctx.fillStyle = C.bg2;
    ctx.fillRect(0, 0, w, h);

    // Grid lines + Y labels
    ctx.strokeStyle = C.bdr;
    ctx.lineWidth = 1;
    ctx.fillStyle = C.dim;
    ctx.font = '11px sans-serif';
    ctx.textAlign = 'right';
    const ySteps = 5;
    for (let i = 0; i <= ySteps; i++) {
        const val = Math.round(maxLen * i / ySteps);
        const yy  = PAD.t + ch - (i / ySteps) * ch;
        ctx.fillText(val, PAD.l - 6, yy + 4);
        ctx.beginPath(); ctx.moveTo(PAD.l, yy); ctx.lineTo(PAD.l + cw, yy);
        ctx.stroke();
    }

    // Bars
    const barW = (cw / buckets.length) * 0.65;
    const gap  = cw / buckets.length;
    const hitAreas = [];

    buckets.forEach((b, i) => {
        const maxSev = b.items.reduce((m, item) => Math.max(m, item.s || 0), 0);
        const color  = maxSev > 0 ? sevColor(maxSev) : C.acc;
        const bh     = (b.items.length / maxLen) * ch;
        const bx     = PAD.l + i * gap + (gap - barW) / 2;
        const by     = PAD.t + ch - bh;

        // Bar body
        ctx.fillStyle = color + '33';
        ctx.fillRect(px(bx), px(by), px(barW), px(bh));
        ctx.fillStyle = color;
        ctx.fillRect(px(bx), px(by), px(barW), 3);

        // Count label
        ctx.fillStyle = C.txt;
        ctx.textAlign = 'center';
        ctx.font = 'bold 14px sans-serif';
        ctx.fillText(b.items.length, px(bx + barW / 2), px(by - 6));

        // Bucket label
        ctx.fillStyle = C.dim;
        ctx.font = '11px sans-serif';
        ctx.fillText(b.label, px(bx + barW / 2), h - PAD.b + 18);

        // Suspicious count label
        const suspCount = b.items.filter(x => x.s >= 3).length;
        if (suspCount > 0) {
            ctx.fillStyle = C.red;
            ctx.font = '10px sans-serif';
            ctx.fillText(`${suspCount} flagged`, px(bx + barW / 2), h - PAD.b + 32);
        }

        hitAreas.push({x: bx, y: by, w: barW, h: bh, bucket: b});
    });

    // Axis label
    ctx.fillStyle = C.dim;
    ctx.font = '11px sans-serif';
    ctx.textAlign = 'left';
    ctx.save(); ctx.translate(12, PAD.t + ch / 2); ctx.rotate(-Math.PI / 2);
    ctx.textAlign = 'center'; ctx.fillText('# of executables', 0, 0); ctx.restore();

    // Interaction
    cv.onmousemove = function(e) {
        const r = cv.getBoundingClientRect();
        const mx = e.clientX - r.left, my = e.clientY - r.top;
        let hit = null;
        for (const h of hitAreas) {
            if (mx >= h.x && mx <= h.x + h.w && my >= h.y && my <= h.y + h.h) { hit = h; break; }
        }
        if (hit) {
            const topN = hit.bucket.items
                .sort((a,b) => (b.s||0) - (a.s||0))
                .slice(0, 12)
                .map(x => `<div style="color:${sevColor(x.s||0)}">${x.n} (${x.r}×)</div>`)
                .join('');
            showTip(tip, cv, mx, my,
                `<strong>${hit.bucket.label}</strong> — ${hit.bucket.items.length} executables<br>${topN}` +
                (hit.bucket.items.length > 12 ? `<div style="color:${C.dim}">…and ${hit.bucket.items.length-12} more</div>` : ''));
        } else { hideTip(tip); }
    };
    cv.onmouseleave = () => hideTip(tip);
}

// ─────────────────────────────────────────────────────────────────────────────
// CHART 2 — Execution Timeline (dot-per-event, per-exe lanes)
// ─────────────────────────────────────────────────────────────────────────────
function renderTimeline() {
    const S = setupCanvas('canvas-timeline');
    if (!S) return;
    const {cv, ctx, w, h} = S;
    const tip = document.getElementById('timeline-tooltip');

    const events = CHART_DATA.timeline;
    if (!events || events.length === 0) { drawEmpty(ctx, w, h, 'No execution events'); return; }

    // Build sorted unique exe list (by first occurrence)
    const exeOrder = [];
    const exeSeen = new Set();
    events.forEach(ev => { if (!exeSeen.has(ev.e)) { exeSeen.add(ev.e); exeOrder.push(ev.e); } });

    const exeIdx = {};
    exeOrder.forEach((e, i) => { exeIdx[e] = i; });

    const nExe = exeOrder.length;
    const tMin = events[0].t;
    const tMax = events[events.length - 1].t || tMin + 1;
    const tRange = tMax - tMin || 1;

    const PAD = {t:10, r:20, b:38, l:8};
    const laneH = Math.max(3, Math.min(14, (h - PAD.t - PAD.b) / nExe));
    const chartH = nExe * laneH;
    const cvH = chartH + PAD.t + PAD.b;

    // Resize canvas to fit all lanes
    const dpr = window.devicePixelRatio || 1;
    cv.width  = (w) * dpr;
    cv.height = cvH * dpr;
    cv.style.width  = w + 'px';
    cv.style.height = cvH + 'px';
    ctx.scale(dpr, dpr);

    // Background
    ctx.fillStyle = C.bg2;
    ctx.fillRect(0, 0, w, cvH);

    // Alternating lane backgrounds
    exeOrder.forEach((_, i) => {
        const ly = PAD.t + i * laneH;
        ctx.fillStyle = i % 2 === 0 ? '#ffffff08' : '#00000000';
        ctx.fillRect(0, ly, w, laneH);
    });

    // Time axis ticks
    const tickCount = Math.min(8, Math.floor(w / 90));
    ctx.strokeStyle = C.bdr; ctx.lineWidth = 1; ctx.fillStyle = C.dim; ctx.font = '10px sans-serif';
    ctx.textAlign = 'center';
    for (let i = 0; i <= tickCount; i++) {
        const t = tMin + (tRange * i / tickCount);
        const x = PAD.l + ((t - tMin) / tRange) * (w - PAD.l - PAD.r);
        ctx.beginPath(); ctx.moveTo(x, PAD.t); ctx.lineTo(x, PAD.t + chartH); ctx.stroke();
        const d = new Date(t);
        const label = d.toISOString().replace('T', ' ').slice(0, 16);
        ctx.fillText(label, x, cvH - 8);
    }

    // Dot radius
    const R = Math.max(2, Math.min(4, laneH * 0.35));

    // Plot dots
    const hitDots = [];
    events.forEach(ev => {
        const x = PAD.l + ((ev.t - tMin) / tRange) * (w - PAD.l - PAD.r);
        const y = PAD.t + exeIdx[ev.e] * laneH + laneH / 2;
        const col = ev.s > 0 ? sevColor(ev.s) : C.acc;
        ctx.beginPath();
        ctx.arc(px(x), px(y), R, 0, Math.PI * 2);
        ctx.fillStyle = col + 'cc';
        ctx.fill();
        hitDots.push({x, y, ev, R: R + 4});
    });

    cv.onmousemove = function(e) {
        const r = cv.getBoundingClientRect();
        const mx = e.clientX - r.left, my = e.clientY - r.top;
        let best = null, bestD = 99999;
        for (const d of hitDots) {
            const dist = Math.hypot(mx - d.x, my - d.y);
            if (dist < d.R && dist < bestD) { bestD = dist; best = d; }
        }
        if (best) {
            const col = sevColor(best.ev.s);
            showTip(tip, cv, mx, my,
                `<strong style="color:${col}">${best.ev.e}</strong><br>` +
                `${best.ev.ts}<br>` +
                (best.ev.s > 0 ? `<span style="color:${col}">${SEV_LABEL[best.ev.s]}</span><br>` : '') +
                `Hash: <code>${best.ev.h}</code>`);
        } else { hideTip(tip); }
    };
    cv.onmouseleave = () => hideTip(tip);
}

// ─────────────────────────────────────────────────────────────────────────────
// CHART 3 — Execution Burst area chart
// ─────────────────────────────────────────────────────────────────────────────
function renderBurst() {
    const S = setupCanvas('canvas-burst');
    if (!S) return;
    const {cv, ctx, w, h} = S;
    const tip = document.getElementById('burst-tooltip');

    const pts = CHART_DATA.burst;
    if (!pts || pts.length < 2) { drawEmpty(ctx, w, h, 'Insufficient data'); return; }

    const PAD = {t:20, r:20, b:50, l:46};
    const cw = w - PAD.l - PAD.r;
    const ch = h - PAD.t - PAD.b;

    const tMin  = pts[0].t;
    const tMax  = pts[pts.length-1].t || tMin + 1;
    const tRng  = tMax - tMin || 1;
    const maxC  = Math.max(...pts.map(p => p.c), 1);
    const ALERT = 5; // burst threshold

    ctx.fillStyle = C.bg2; ctx.fillRect(0, 0, w, h);

    // Grid + Y labels
    const ySteps = 5;
    ctx.strokeStyle = C.bdr; ctx.lineWidth = 1;
    ctx.fillStyle = C.dim; ctx.font = '11px sans-serif'; ctx.textAlign = 'right';
    for (let i = 0; i <= ySteps; i++) {
        const val = Math.round(maxC * i / ySteps);
        const yy  = PAD.t + ch - (i / ySteps) * ch;
        ctx.fillText(val, PAD.l - 6, yy + 4);
        ctx.beginPath(); ctx.moveTo(PAD.l, yy); ctx.lineTo(PAD.l + cw, yy); ctx.stroke();
    }

    // Alert threshold line
    if (ALERT <= maxC) {
        const yAlert = PAD.t + ch - (ALERT / maxC) * ch;
        ctx.strokeStyle = C.red + '88'; ctx.lineWidth = 1; ctx.setLineDash([4, 4]);
        ctx.beginPath(); ctx.moveTo(PAD.l, yAlert); ctx.lineTo(PAD.l + cw, yAlert); ctx.stroke();
        ctx.setLineDash([]);
        ctx.fillStyle = C.red; ctx.font = '10px sans-serif'; ctx.textAlign = 'left';
        ctx.fillText('alert threshold (5)', PAD.l + 4, yAlert - 3);
    }

    // X ticks
    const tickN = Math.min(6, Math.floor(cw / 80));
    ctx.fillStyle = C.dim; ctx.font = '10px sans-serif'; ctx.textAlign = 'center';
    for (let i = 0; i <= tickN; i++) {
        const t = tMin + (tRng * i / tickN);
        const x = PAD.l + ((t - tMin) / tRng) * cw;
        const d = new Date(t);
        const lb = d.toISOString().slice(0, 16).replace('T', '\n');
        lb.split('\n').forEach((line, li) => ctx.fillText(line, x, h - PAD.b + 14 + li * 12));
    }

    // Compute polygon points
    const pxPts = pts.map(p => ({
        x: PAD.l + ((p.t - tMin) / tRng) * cw,
        y: PAD.t + ch - (p.c / maxC) * ch,
        p,
    }));

    // Area fill — split into alert (above threshold) / normal
    const alertY = ALERT > maxC ? PAD.t : (PAD.t + ch - (ALERT / maxC) * ch);

    // Normal area (below alert)
    ctx.beginPath();
    ctx.moveTo(pxPts[0].x, PAD.t + ch);
    pxPts.forEach(({x, y}) => ctx.lineTo(x, y));
    ctx.lineTo(pxPts[pxPts.length-1].x, PAD.t + ch);
    ctx.closePath();
    ctx.fillStyle = C.blu + '22';
    ctx.fill();

    // Alert area (above threshold)
    ctx.beginPath();
    pxPts.forEach(({x, y}, i) => {
        const clippedY = Math.min(y, alertY);
        if (i === 0) ctx.moveTo(x, PAD.t + ch);
        ctx.lineTo(x, clippedY);
    });
    ctx.lineTo(pxPts[pxPts.length-1].x, PAD.t + ch);
    ctx.closePath();
    ctx.fillStyle = C.red + '22';
    ctx.fill();

    // Line on top
    ctx.beginPath();
    pxPts.forEach(({x, y}, i) => (i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y)));
    ctx.strokeStyle = C.blu; ctx.lineWidth = 2; ctx.stroke();

    // Dots at burst peaks
    pxPts.forEach(({x, y, p}) => {
        if (p.c >= ALERT) {
            ctx.beginPath(); ctx.arc(x, y, 4, 0, Math.PI*2);
            ctx.fillStyle = C.red; ctx.fill();
        }
    });

    // Interaction
    cv.onmousemove = function(e) {
        const r  = cv.getBoundingClientRect();
        const mx = e.clientX - r.left;
        // Find nearest point
        let best = pxPts[0], bestD = Infinity;
        pxPts.forEach(p => { const d = Math.abs(p.x - mx); if (d < bestD) { bestD = d; best = p; } });
        if (bestD < 30) {
            const col = best.p.c >= ALERT ? C.red : C.blu;
            showTip(tip, cv, mx, best.y,
                `<span style="color:${col}"><strong>${best.p.c} unique processes</strong></span><br>${best.p.ts}<br>` +
                (best.p.c >= ALERT ? `<span style="color:${C.red}">⚠ Burst detected</span>` : ''));
        } else { hideTip(tip); }
    };
    cv.onmouseleave = () => hideTip(tip);
}

// ─────────────────────────────────────────────────────────────────────────────
// CHART 4 — File Path Treemap
// ─────────────────────────────────────────────────────────────────────────────
function renderTreemap() {
    const S = setupCanvas('canvas-treemap');
    if (!S) return;
    const {cv, ctx, w, h} = S;
    const tip = document.getElementById('treemap-tooltip');

    const nodes = CHART_DATA.treemap;
    if (!nodes || nodes.length === 0) { drawEmpty(ctx, w, h, 'No data'); return; }

    ctx.fillStyle = C.bg2; ctx.fillRect(0, 0, w, h);

    const PAD = {t:4, r:4, b:4, l:4};
    const cw = w - PAD.l - PAD.r;
    const ch = h - PAD.t - PAD.b;

    const totalRuns = nodes.reduce((s, n) => s + (n.r || 0), 0) || 1;

    // Simple slice-and-dice treemap layout
    function layout(items, x, y, bw, bh) {
        const total = items.reduce((s, n) => s + (n.r || 0), 0) || 1;
        const boxes = [];
        let cx = x, cy = y;
        const horizontal = bw >= bh;
        items.forEach(item => {
            const frac = (item.r || 0) / total;
            let rx, ry, rw, rh;
            if (horizontal) {
                rw = frac * bw;
                rh = bh;
                rx = cx; ry = cy;
                cx += rw;
            } else {
                rw = bw;
                rh = frac * bh;
                rx = cx; ry = cy;
                cy += rh;
            }
            boxes.push({item, rx, ry, rw, rh});
        });
        return boxes;
    }

    const boxes = layout(nodes, PAD.l, PAD.t, cw, ch);

    boxes.forEach(({item, rx, ry, rw, rh}) => {
        if (rw < 2 || rh < 2) return;

        const isSupp = item.susp;
        const fillC  = isSupp ? (item.s >= 4 ? C.red : C.susp) :
                        item.s >= 4 ? C.red + '66' :
                        item.s >= 3 ? C.yel + '44' :
                        C.acc + '22';
        const brdC   = isSupp ? (item.s >= 4 ? C.red : C.susp) :
                        item.s >= 3 ? C.yel :
                        C.bdr;

        ctx.fillStyle = fillC;
        ctx.fillRect(px(rx)+1, px(ry)+1, px(rw)-2, px(rh)-2);
        ctx.strokeStyle = brdC;
        ctx.lineWidth = 1;
        ctx.strokeRect(px(rx)+1, px(ry)+1, px(rw)-2, px(rh)-2);

        // Label if big enough
        if (rw > 60 && rh > 20) {
            ctx.fillStyle = isSupp ? '#fff' : C.txt;
            ctx.font = rh > 40 ? 'bold 11px sans-serif' : '10px sans-serif';
            ctx.textAlign = 'left';
            // Extract last meaningful dir segment
            const parts = item.n.split('\\').filter(Boolean);
            const label = parts.slice(-2).join('\\') || item.n;
            const maxChars = Math.floor(rw / 6.5);
            const t = label.length > maxChars ? label.slice(0, maxChars - 2) + '…' : label;
            ctx.fillText(t, px(rx)+5, px(ry)+14);
            if (rh > 32) {
                ctx.fillStyle = C.dim;
                ctx.font = '10px sans-serif';
                ctx.fillText(`${item.r} runs · ${(item.c||[]).length} exes`, px(rx)+5, px(ry)+26);
            }
        }
    });

    // Legend
    const legendItems = [
        [C.acc + '22', C.bdr, 'Normal system path'],
        [C.yel + '44', C.yel, 'Medium/flagged (system path)'],
        [C.susp, C.susp, 'Suspicious path'],
        [C.red, C.red, 'Critical/High suspicious'],
    ];
    let lx = PAD.l + 4;
    const ly = h - 2;
    ctx.font = '10px sans-serif';
    legendItems.forEach(([fill, brd, label]) => {
        ctx.fillStyle = fill; ctx.strokeStyle = brd; ctx.lineWidth = 1;
        ctx.fillRect(lx, ly - 10, 14, 10); ctx.strokeRect(lx, ly - 10, 14, 10);
        ctx.fillStyle = C.dim; ctx.textAlign = 'left';
        ctx.fillText(label, lx + 18, ly - 1);
        lx += ctx.measureText(label).width + 40;
    });

    // Interaction
    cv.onmousemove = function(e) {
        const r  = cv.getBoundingClientRect();
        const mx = e.clientX - r.left, my = e.clientY - r.top;
        for (const {item, rx, ry, rw, rh} of boxes) {
            if (mx >= rx && mx <= rx + rw && my >= ry && my <= ry + rh) {
                const topExes = (item.c || [])
                    .sort((a, b) => (b.r || 0) - (a.r || 0))
                    .slice(0, 8)
                    .map(x => `<div><span style="color:${sevColor(x.s||0)}">${x.n}</span> — ${x.r}× </div>`)
                    .join('');
                showTip(tip, cv, mx, my,
                    `<strong>${item.n}</strong><br>${item.r} total runs · ${(item.c||[]).length} executables` +
                    (item.susp ? `<br><span style="color:${C.susp}">⚠ Suspicious path</span>` : '') +
                    (topExes ? '<hr>' + topExes : ''));
                return;
            }
        }
        hideTip(tip);
    };
    cv.onmouseleave = () => hideTip(tip);
}

// ─────────────────────────────────────────────────────────────────────────────
// CHART 5 — DLL Radial graphs
// ─────────────────────────────────────────────────────────────────────────────
function renderDllRadial() {
    const container = document.getElementById('dll-radial-container');
    if (!container) return;
    const graphs = CHART_DATA.dlls;

    if (!graphs || graphs.length === 0) {
        container.innerHTML = '<div style="color:#8b949e;padding:20px;text-align:center;">No flagged executables with DLL data found.</div>';
        return;
    }

    graphs.forEach(graph => {
        const wrap = document.createElement('div');
        wrap.className = 'dll-svg-wrap';

        const title = document.createElement('div');
        title.className = 'dll-title';
        title.style.color = sevColor(graph.sev || 0);
        title.textContent = graph.exe;
        wrap.appendChild(title);

        const SVG_W = 380, SVG_H = 380;
        const cx = SVG_W / 2, cy = SVG_H / 2;
        const R_center = 32, R_dll = 11;
        const R_inner = 60, R_outer = 155;

        const dlls = graph.dlls || [];
        const sysDlls  = dlls.filter(d => d.sys && !d.susp);
        const suspDlls = dlls.filter(d => d.susp);
        const otherDlls = dlls.filter(d => !d.sys && !d.susp);

        // Build display sets: non-system first, suspicious highlighted
        const displayOrder = [...suspDlls, ...otherDlls, ...sysDlls].slice(0, 52);
        const nDlls = displayOrder.length;

        const ns = 'http://www.w3.org/2000/svg';
        const svg = document.createElementNS(ns, 'svg');
        svg.setAttribute('viewBox', `0 0 ${SVG_W} ${SVG_H}`);
        svg.setAttribute('width', SVG_W);
        svg.setAttribute('height', SVG_H);
        svg.style.background = C.bg2;
        svg.style.borderRadius = '6px';
        svg.style.border = `1px solid ${C.bdr}`;

        // Defs: glow filters
        const defs = document.createElementNS(ns, 'defs');
        const filter = document.createElementNS(ns, 'filter');
        filter.id = 'glow-' + graph.exe.replace(/\W/g,'');
        const feBlur = document.createElementNS(ns, 'feGaussianBlur');
        feBlur.setAttribute('stdDeviation', '2'); feBlur.setAttribute('result', 'blur');
        const feMerge = document.createElementNS(ns, 'feMerge');
        [document.createElementNS(ns, 'feMergeNode'), document.createElementNS(ns, 'feMergeNode')]
            .forEach((n, i) => { if (i===1) n.setAttribute('in', 'SourceGraphic'); feMerge.appendChild(n); });
        filter.appendChild(feBlur); filter.appendChild(feMerge);
        defs.appendChild(filter);
        svg.appendChild(defs);

        // Concentric ring decorations
        [R_inner - 10, R_outer + 18].forEach(r => {
            const circle = document.createElementNS(ns, 'circle');
            circle.setAttribute('cx', cx); circle.setAttribute('cy', cy);
            circle.setAttribute('r', r);
            circle.setAttribute('fill', 'none');
            circle.setAttribute('stroke', C.bdr);
            circle.setAttribute('stroke-width', '1');
            svg.appendChild(circle);
        });

        // DLL spokes
        const tooltip = document.createElement('div');
        tooltip.className = 'chart-tooltip';
        tooltip.style.position = 'fixed';
        document.body.appendChild(tooltip);

        displayOrder.forEach((dll, i) => {
            const angle = (i / nDlls) * 2 * Math.PI - Math.PI / 2;
            // Use two rings: inner for non-sys, outer for sys
            const ringR = dll.sys && !dll.susp ? R_outer : R_inner + (R_outer - R_inner) * 0.4;

            const nx = cx + ringR * Math.cos(angle);
            const ny = cy + ringR * Math.sin(angle);

            const color = dll.susp ? C.red : dll.sys ? C.dim : '#eac54f';

            // Spoke line
            const line = document.createElementNS(ns, 'line');
            line.setAttribute('x1', cx); line.setAttribute('y1', cy);
            line.setAttribute('x2', nx); line.setAttribute('y2', ny);
            line.setAttribute('stroke', color + '55'); line.setAttribute('stroke-width', '1');
            svg.appendChild(line);

            // DLL node circle
            const circle = document.createElementNS(ns, 'circle');
            circle.setAttribute('cx', nx); circle.setAttribute('cy', ny);
            circle.setAttribute('r', dll.susp ? R_dll + 3 : R_dll);
            circle.setAttribute('fill', color + (dll.susp ? 'cc' : '44'));
            circle.setAttribute('stroke', color);
            circle.setAttribute('stroke-width', dll.susp ? '2' : '1');
            circle.style.cursor = 'pointer';
            if (dll.susp) circle.setAttribute('filter', `url(#glow-${graph.exe.replace(/\W/g,'')})`);

            // DLL label (only for non-system / suspicious)
            if (!dll.sys || dll.susp) {
                const text = document.createElementNS(ns, 'text');
                const shortName = dll.n.replace(/(\.DLL|\.SYS)$/i, '').slice(0, 12);
                const textAngle = (angle * 180 / Math.PI) + 90;
                text.setAttribute('x', nx); text.setAttribute('y', ny - R_dll - 3);
                text.setAttribute('text-anchor', 'middle');
                text.setAttribute('font-size', '8');
                text.setAttribute('fill', color);
                text.setAttribute('transform', `rotate(${textAngle},${nx},${ny})`);
                text.textContent = shortName;
                svg.appendChild(text);
            }

            circle.addEventListener('mouseenter', function(e) {
                tooltip.innerHTML =
                    `<strong style="color:${color}">${dll.n}</strong><br>` +
                    `<span style="font-size:11px;word-break:break-all">${dll.p}</span><br>` +
                    (dll.susp ? `<span style="color:${C.red}">⚠ Suspicious DLL</span>`: '') +
                    (dll.sys  ? `<span style="color:${C.dim}">System DLL</span>` : '') +
                    (!dll.sys && !dll.susp ? `<span style="color:#eac54f">Non-system DLL</span>` : '');
                tooltip.style.display = 'block';
                tooltip.style.left = (e.clientX + 14) + 'px';
                tooltip.style.top  = (e.clientY + 14) + 'px';
            });
            circle.addEventListener('mouseleave', function() { tooltip.style.display = 'none'; });
            svg.appendChild(circle);
        });

        // Center: executable name
        const cBg = document.createElementNS(ns, 'circle');
        cBg.setAttribute('cx', cx); cBg.setAttribute('cy', cy);
        cBg.setAttribute('r', R_center);
        cBg.setAttribute('fill', sevColor(graph.sev || 0) + '33');
        cBg.setAttribute('stroke', sevColor(graph.sev || 0));
        cBg.setAttribute('stroke-width', '2');
        svg.appendChild(cBg);

        const cText = document.createElementNS(ns, 'text');
        cText.setAttribute('x', cx); cText.setAttribute('y', cy + 4);
        cText.setAttribute('text-anchor', 'middle');
        cText.setAttribute('font-size', '9');
        cText.setAttribute('font-weight', 'bold');
        cText.setAttribute('fill', sevColor(graph.sev || 0));
        cText.textContent = graph.exe.replace(/(\.EXE|\.DLL)$/i, '');
        svg.appendChild(cText);

        // Legend inside SVG
        const legendY = SVG_H - 16;
        [
            [C.red, 'Suspicious'],
            ['#eac54f', 'Non-system'],
            [C.dim, 'System'],
        ].forEach(([col, label], i) => {
            const lx = 10 + i * 110;
            const lc = document.createElementNS(ns, 'circle');
            lc.setAttribute('cx', lx + 5); lc.setAttribute('cy', legendY);
            lc.setAttribute('r', '5'); lc.setAttribute('fill', col + '88');
            lc.setAttribute('stroke', col); lc.setAttribute('stroke-width','1');
            svg.appendChild(lc);
            const lt = document.createElementNS(ns, 'text');
            lt.setAttribute('x', lx + 14); lt.setAttribute('y', legendY + 4);
            lt.setAttribute('font-size', '9'); lt.setAttribute('fill', col);
            lt.textContent = label;
            svg.appendChild(lt);
        });

        // DLL count badge
        const badge = document.createElementNS(ns, 'text');
        badge.setAttribute('x', cx);
        badge.setAttribute('y', SVG_H - 16);
        badge.setAttribute('text-anchor', 'middle');
        badge.setAttribute('font-size', '9');
        badge.setAttribute('fill', C.dim);
        badge.textContent = `${dlls.length} files loaded (showing ${Math.min(52, dlls.length)})`;
        svg.appendChild(badge);

        wrap.appendChild(svg);
        container.appendChild(wrap);
    });
}

// ─── Utility: draw "empty state" ────────────────────────────────────────────
function drawEmpty(ctx, w, h, msg) {
    ctx.fillStyle = '#1f2428'; ctx.fillRect(0, 0, w, h);
    ctx.fillStyle = '#8b949e'; ctx.font = '13px sans-serif';
    ctx.textAlign = 'center'; ctx.fillText(msg, w/2, h/2);
}

// ─── Boot ────────────────────────────────────────────────────────────────────
function renderAll() {
    renderHistogram();
    renderTimeline();
    renderBurst();
    renderTreemap();
    renderDllRadial();
}

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderAll);
} else {
    renderAll();
}

window.addEventListener('resize', function() {
    clearTimeout(window._chartResizeTimer);
    window._chartResizeTimer = setTimeout(renderAll, 180);
});

})(); // end IIFE
</script>
"#);

    html
}


// ─────────────────────────────────────────────────────────────────────────────
//  New report-section helpers (HTML)
// ─────────────────────────────────────────────────────────────────────────────

/// Renders the **Complete Prefetch Entry Table** section.
/// Includes every parsed prefetch entry with its 8-char hash, run count,
/// first/last execution timestamp, file-load count, and resolved exe path.
pub fn generate_complete_entry_table_html(entries: &[PrefetchEntry]) -> String {
    let mut html = String::new();

    html.push_str(r#"
        <div class="category-header" id="section-entry-table" style="border-left-color: #58a6ff;">
            <span class="icon"></span>
            <h3>🗂️ Complete Prefetch Entry Table</h3>
"#);
    html.push_str(&format!(
        r#"<span class="category-count">{} entries</span></div>
"#,
        entries.len()
    ));

    // Sort entries by last execution time (most recent first)
    let mut sorted: Vec<&PrefetchEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| b.last_run().cmp(&a.last_run()));

    html.push_str(r#"
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table id="entry-table">
            <thead>
                <tr>
                    <th>Prefetch File</th>
                    <th>Hash</th>
                    <th>Executable</th>
                    <th>Run Count</th>
                    <th>First Run</th>
                    <th>Last Run</th>
                    <th>Files Loaded</th>
                    <th>Execution Path</th>
                </tr>
            </thead>
            <tbody>
"#);

    for entry in &sorted {
        let hash = entry.extract_prefetch_hash().unwrap_or_else(|| "?".to_string());
        let pf_base = std::path::Path::new(&entry.filename)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&entry.filename);
        let first = entry.first_run()
            .map(|t| t.format("%Y-%m-%d %H:%M:%S").to_string())
            .unwrap_or_else(|| "-".to_string());
        let last = entry.last_run()
            .map(|t| t.format("%Y-%m-%d %H:%M:%S").to_string())
            .unwrap_or_else(|| "-".to_string());
        let exe_path = entry
            .get_executable_path()
            .unwrap_or_else(|| "-".to_string());

        html.push_str(&format!(
            r#"
                <tr>
                    <td><code style="font-size:11px;">{}</code></td>
                    <td><code style="color:#58a6ff;">{}</code></td>
                    <td><code>{}</code></td>
                    <td style="text-align:center;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="text-align:center;">{}</td>
                    <td style="font-size:11px;word-break:break-all;">{}</td>
                </tr>
"#,
            html_escape(pf_base),
            html_escape(&hash),
            html_escape(&entry.executable_name),
            entry.run_count(),
            html_escape(&first),
            html_escape(&last),
            entry.num_files,
            html_escape(&exe_path),
        ));
    }

    html.push_str(r#"
            </tbody>
        </table>
        </div>
"#);

    html
}

/// Renders the **Execution Timestamps** section — every recorded timestamp
/// for every prefetch entry, grouped by executable, sorted newest-first.
pub fn generate_timestamps_html(entries: &[PrefetchEntry]) -> String {
    let mut html = String::new();

    // Sort entries by last run (most recent activity first)
    let mut sorted: Vec<&PrefetchEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| b.last_run().cmp(&a.last_run()));

    html.push_str(&format!(r#"
        <div class="category-header" id="section-timestamps" style="border-left-color: #d29922;">
            <span class="icon"></span>
            <h3>⏱️ Execution Timestamps (All Entries)</h3>
            <span class="category-count">{} executables</span>
        </div>
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table>
            <thead>
                <tr>
                    <th>Executable</th>
                    <th>Prefetch Hash</th>
                    <th>Run #</th>
                    <th>Timestamp</th>
                </tr>
            </thead>
            <tbody>
"#, sorted.len()));

    for entry in &sorted {
        let hash = entry.extract_prefetch_hash().unwrap_or_else(|| "?".to_string());
        let mut times = entry.get_run_times();
        times.sort_by(|a, b| b.cmp(a)); // newest first

        for (run_idx, ts) in times.iter().enumerate() {
            html.push_str(&format!(
                r#"
                <tr>
                    <td><code>{}</code></td>
                    <td><code style="color:#58a6ff;">{}</code></td>
                    <td style="text-align:center;color:var(--text-secondary);">Run {}</td>
                    <td style="font-family:'SF Mono','Fira Code',monospace;font-size:13px;">{}</td>
                </tr>
"#,
                html_escape(&entry.executable_name),
                html_escape(&hash),
                run_idx + 1,
                ts.format("%Y-%m-%d %H:%M:%S%.3f"),
            ));
        }
    }

    html.push_str(r#"
            </tbody>
        </table>
        </div>
"#);

    html
}

/// Renders the **Full Executable Timeline** — every execution event from every
/// prefetch entry in strict chronological order (oldest → newest), with the
/// originating executable and prefetch hash annotated per row.
pub fn generate_timeline_html(entries: &[PrefetchEntry]) -> String {
    // Collect (timestamp, executable_name, hash) tuples
    let mut events: Vec<(chrono::NaiveDateTime, String, String)> = Vec::new();

    for entry in entries {
        let hash = entry.extract_prefetch_hash().unwrap_or_else(|| "?".to_string());
        for ts in entry.get_run_times() {
            events.push((ts, entry.executable_name.clone(), hash.clone()));
        }
    }

    // Sort chronologically
    events.sort_by_key(|(ts, _, _)| *ts);

    let mut html = String::new();

    html.push_str(&format!(r#"
        <div class="category-header" id="section-timeline" style="border-left-color: #3fb950;">
            <span class="icon"></span>
            <h3>📅 Full Executable Timeline</h3>
            <span class="category-count">{} execution events</span>
        </div>
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Timestamp</th>
                    <th>Executable</th>
                    <th>Prefetch Hash</th>
                </tr>
            </thead>
            <tbody>
"#, events.len()));

    for (i, (ts, exe, hash)) in events.iter().enumerate() {
        html.push_str(&format!(
            r#"
                <tr>
                    <td style="text-align:center;color:var(--text-secondary);font-size:12px;">{}</td>
                    <td style="font-family:'SF Mono','Fira Code',monospace;font-size:13px;">{}</td>
                    <td><code>{}</code></td>
                    <td><code style="color:#58a6ff;">{}</code></td>
                </tr>
"#,
            i + 1,
            ts.format("%Y-%m-%d %H:%M:%S%.3f"),
            html_escape(exe),
            html_escape(hash),
        ));
    }

    html.push_str(r#"
            </tbody>
        </table>
        </div>
"#);

    html
}

/// Minimal HTML entity escaping to prevent XSS in report output.
fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn truncate(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        s.to_string()
    } else {
        format!("{}...", &s[..max_len-3])
    }
}
