//! Report Generation
//!
//! Generates reports in various formats (JSON, Markdown, HTML).

use crate::models::{AnalysisReport, Finding, PrefetchEntry, Severity};
use anyhow::Result;
use std::fs;
use std::path::Path;

/// Generate a JSON report
pub fn generate_json_report(report: &AnalysisReport) -> Result<String> {
    let payload = serde_json::json!({
        "generated_at": report.generated_at,
        "total_entries": report.total_entries,
        "unique_executables": report.unique_executables,
        "date_range": report.date_range,
        "summary": report.summary,
        "findings": report.findings,
        "entries": report.raw_entries,
    });
    Ok(serde_json::to_string_pretty(&payload)?)
}

/// Generate a Markdown report
pub fn generate_markdown_report(report: &AnalysisReport) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# 🔍 Windows Prefetch Analysis Report\n\n");
    md.push_str(&format!("**Generated:** {}\n\n", report.generated_at.format("%Y-%m-%d %H:%M:%S UTC")));

    // Summary Section
    md.push_str("## 📊 Executive Summary\n\n");
    md.push_str("| Metric | Value |\n");
    md.push_str("|--------|-------|\n");
    md.push_str(&format!("| Total Prefetch Entries | {} |\n", report.total_entries));
    md.push_str(&format!("| Unique Executables | {} |\n", report.unique_executables));
    
    if let Some((start, end)) = report.date_range {
        md.push_str(&format!("| Date Range | {} to {} |\n", 
            start.format("%Y-%m-%d %H:%M"),
            end.format("%Y-%m-%d %H:%M")));
    }
    md.push_str(&format!("| Total Findings | {} |\n\n", report.summary.total()));

    // Severity Breakdown
    md.push_str("### Findings by Severity\n\n");
    md.push_str(&format!("- 🔴 **Critical:** {}\n", report.summary.critical));
    md.push_str(&format!("- 🟠 **High:** {}\n", report.summary.high));
    md.push_str(&format!("- 🟡 **Medium:** {}\n", report.summary.medium));
    md.push_str(&format!("- 🔵 **Low:** {}\n", report.summary.low));
    md.push_str(&format!("- ℹ️ **Info:** {}\n\n", report.summary.info));

    // Critical and High Findings
    let critical_high: Vec<_> = report.findings.iter()
        .filter(|f| f.severity >= Severity::High)
        .collect();

    if !critical_high.is_empty() {
        md.push_str("## 🚨 Critical & High Severity Findings\n\n");
        for finding in critical_high {
            md.push_str(&format_finding_md(finding));
        }
    }

    // All Findings Table
    md.push_str("## 📋 All Findings\n\n");
    md.push_str("| Severity | Executable | Category | Description | MITRE ATT&CK |\n");
    md.push_str("|----------|------------|----------|-------------|---------------|\n");

    for finding in &report.findings {
        let mitre = finding.mitre_attack.as_deref().unwrap_or("-");
        md.push_str(&format!(
            "| {} {} | `{}` | {} | {} | {} |\n",
            finding.severity.emoji(),
            finding.severity,
            finding.executable,
            finding.category,
            truncate(&finding.description, 50),
            mitre
        ));
    }

    // MITRE ATT&CK Mapping
    let mitre_findings: Vec<_> = report.findings.iter()
        .filter(|f| f.mitre_attack.is_some())
        .collect();

    if !mitre_findings.is_empty() {
        md.push_str("\n## 🎯 MITRE ATT&CK Mapping\n\n");
        md.push_str("| Technique ID | Technique Name | Executable | Description |\n");
        md.push_str("|--------------|----------------|------------|-------------|\n");

        for finding in mitre_findings {
            md.push_str(&format!(
                "| {} | {} | `{}` | {} |\n",
                finding.mitre_attack.as_deref().unwrap_or("-"),
                finding.mitre_name.as_deref().unwrap_or("-"),
                finding.executable,
                truncate(&finding.description, 40)
            ));
        }
    }

    // Timeline Section
    md.push_str("\n## ⏱️ Execution Timeline\n\n");
    md.push_str("Executables with the most recent activity:\n\n");
    
    let mut recent: Vec<_> = report.findings.iter()
        .filter(|f| f.last_run.is_some())
        .collect();
    recent.sort_by(|a, b| b.last_run.cmp(&a.last_run));
    recent.truncate(20);

    if !recent.is_empty() {
        md.push_str("| Last Run | Executable | Run Count | Severity |\n");
        md.push_str("|----------|------------|-----------|----------|\n");
        for finding in recent {
            if let Some(last) = finding.last_run {
                md.push_str(&format!(
                    "| {} | `{}` | {} | {} |\n",
                    last.format("%Y-%m-%d %H:%M:%S"),
                    finding.executable,
                    finding.run_count,
                    finding.severity
                ));
            }
        }
    }

    md.push_str("\n---\n");
    md.push_str("*Generated by Windows Prefetch Analyzer*\n");

    md
}

/// Format a single finding for markdown detail view
fn format_finding_md(finding: &Finding) -> String {
    let mut md = String::new();

    md.push_str(&format!("### {} {} - `{}`\n\n", 
        finding.severity.emoji(),
        finding.severity,
        finding.executable
    ));

    md.push_str(&format!("**Category:** {}\n\n", finding.category));
    md.push_str(&format!("**Description:** {}\n\n", finding.description));

    if let Some(ref mitre) = finding.mitre_attack {
        md.push_str(&format!("**MITRE ATT&CK:** {} - {}\n\n", 
            mitre,
            finding.mitre_name.as_deref().unwrap_or("Unknown")
        ));
    }

    if let Some(ref path) = finding.path {
        md.push_str(&format!("**Path:** `{}`\n\n", path));
    }

    if let Some(last) = finding.last_run {
        md.push_str(&format!("**Last Execution:** {} (Run Count: {})\n\n", 
            last.format("%Y-%m-%d %H:%M:%S"),
            finding.run_count
        ));
    }

    if let Some(ref context) = finding.context {
        md.push_str(&format!("**Context:** {}\n\n", context));
    }

    md.push_str("---\n\n");
    md
}

/// Generate HTML report with styled output (KaliHeker theme)
pub fn generate_html_report(report: &AnalysisReport) -> String {
    use std::collections::HashMap;

    let mut html = String::new();
    let entry_by_filename: HashMap<&str, &PrefetchEntry> = report
        .raw_entries
        .iter()
        .map(|e| (e.filename.as_str(), e))
        .collect();

    html.push_str(r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KaliHeker - Prefetch Analysis Report</title>
    <style>
        :root {
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --bg-tertiary: #1f2428;
            --border-color: #30363d;
            --text-primary: #c9d1d9;
            --text-secondary: #8b949e;
            --accent: #238636;
            --accent-light: #2ea043;
            --alert-bg: #da3633;
            --alert-text: #ffebe9;
            --warning-bg: #9e6a03;
            --warning-text: #fff8c5;
            --notice-bg: #238636;
            --notice-text: #f0f6fc;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            line-height: 1.5;
            min-height: 100vh;
        }
        header {
            background: var(--bg-secondary);
            border-bottom: 1px solid var(--border-color);
            padding: 24px;
        }
        .header-content { max-width: 1400px; margin: 0 auto; }
        .logo { display: flex; align-items: center; gap: 16px; margin-bottom: 20px; }
        .logo-text { font-size: 28px; font-weight: 700; color: var(--text-primary); letter-spacing: -0.5px; }
        .logo-text span { color: var(--accent-light); }
        .version { font-size: 14px; color: var(--text-secondary); background: var(--bg-tertiary); padding: 2px 8px; border-radius: 12px; border: 1px solid var(--border-color); }
        .scan-info { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; margin-top: 16px; }
        .info-card { background: var(--bg-tertiary); border: 1px solid var(--border-color); border-radius: 6px; padding: 12px 16px; }
        .info-card h3 { font-size: 12px; text-transform: uppercase; color: var(--text-secondary); margin-bottom: 4px; letter-spacing: 0.5px; }
        .info-card p { font-size: 14px; color: var(--text-primary); word-break: break-all; }
        .score { font-size: 18px; font-weight: 700; color: var(--text-primary); }
        nav {
            background: var(--bg-secondary);
            border-bottom: 1px solid var(--border-color);
            padding: 12px 24px;
            position: sticky;
            top: 0;
            z-index: 100;
            box-shadow: 0 4px 12px rgba(0,0,0,0.2);
        }
        .nav-content { max-width: 1400px; margin: 0 auto; display: flex; flex-wrap: wrap; gap: 16px; align-items: center; justify-content: space-between; }
        .filter-buttons { display: flex; gap: 8px; flex-wrap: wrap; }
        .filter-btn {
            padding: 6px 14px; border: 1px solid var(--border-color); border-radius: 20px;
            background: var(--bg-tertiary); color: var(--text-primary); cursor: pointer; font-size: 13px; transition: all 0.2s;
        }
        .filter-btn:hover { border-color: var(--accent); }
        .filter-btn.active { background: var(--accent); color: #fff; border-color: var(--accent); }
        .filter-btn .count { margin-left: 6px; opacity: 0.8; font-size: 0.9em; }
        .search-box { display: flex; align-items: center; gap: 8px; }
        .search-box input {
            padding: 8px 14px; border: 1px solid var(--border-color); border-radius: 6px;
            background: var(--bg-tertiary); color: var(--text-primary); font-size: 14px; width: 280px;
        }
        .search-box input:focus { outline: none; border-color: var(--accent); box-shadow: 0 0 0 2px rgba(46, 160, 67, 0.4); }
        main { max-width: 1400px; margin: 0 auto; padding: 24px; }
        .stats-bar {
            display: flex; gap: 24px; margin-bottom: 20px; padding: 16px;
            background: var(--bg-secondary); border-radius: 8px; border: 1px solid var(--border-color);
        }
        .stat { display: flex; align-items: center; gap: 8px; }
        .stat-dot { width: 12px; height: 12px; border-radius: 50%; }
        .stat-dot.alert { background: var(--alert-bg); }
        .stat-dot.warning { background: var(--warning-bg); }
        .stat-dot.notice { background: var(--notice-bg); }
        .stat-label { font-size: 14px; color: var(--text-secondary); }
        .stat-value { font-size: 18px; font-weight: 600; }
        .finding-card {
            background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 8px; overflow: hidden;
            margin-bottom: 16px; transition: transform 0.2s; border-left: 4px solid var(--border-color);
        }
        .finding-card:hover { transform: translateY(-2px); border-color: var(--accent); }
        .finding-card.critical { border-left-color: var(--alert-bg); }
        .finding-card.high { border-left-color: #fd8c00; }
        .finding-card.medium { border-left-color: var(--warning-bg); }
        .finding-card.low { border-left-color: var(--notice-bg); }
        .finding-card.info { border-left-color: #1f6feb; }
        .finding-header {
            display: flex; align-items: center; gap: 12px; padding: 16px;
            background: var(--bg-tertiary); border-bottom: 1px solid var(--border-color); flex-wrap: wrap;
        }
        .severity-badge { padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; text-transform: uppercase; }
        .severity-badge.critical { background: var(--alert-bg); color: var(--alert-text); }
        .severity-badge.high { background: #fd8c00; color: #fff; }
        .severity-badge.medium { background: var(--warning-bg); color: var(--warning-text); }
        .severity-badge.low { background: var(--notice-bg); color: var(--notice-text); }
        .severity-badge.info { background: #1f6feb; color: #fff; }
        .finding-title {
            flex: 1; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 14px; font-weight: 600;
            color: var(--accent-light); word-break: break-all;
        }
        .finding-body { padding: 16px; }
        .finding-description { margin-bottom: 16px; color: var(--text-primary); font-size: 14px; }
        .evidence-box {
            background: var(--bg-primary); border: 1px solid var(--border-color); border-radius: 6px; padding: 12px;
            margin-bottom: 12px; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 12px; overflow-x: auto;
        }
        .evidence-line { margin-bottom: 4px; }
        .evidence-label { color: var(--text-secondary); margin-right: 8px; }
        .metadata-tags { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 12px; }
        .meta-tag {
            background: var(--bg-tertiary); border: 1px solid var(--border-color); border-radius: 12px;
            padding: 2px 10px; font-size: 11px; color: var(--text-secondary);
        }
        .meta-tag strong { color: var(--text-primary); }
        .mitre-link { color: var(--accent-light); text-decoration: none; }
        .mitre-link:hover { text-decoration: underline; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid var(--border-color); }
        th { background: var(--bg-tertiary); color: var(--accent-light); font-size: 12px; text-transform: uppercase; }
        tr:hover { background: rgba(255,255,255,0.03); }
        code {
            background: var(--bg-primary); padding: 2px 6px; border-radius: 4px;
            font-family: 'SF Mono', 'Fira Code', 'Consolas', monospace; font-size: 13px;
        }
        footer {
            text-align: center; padding: 40px 20px; color: var(--text-secondary); font-size: 13px;
            border-top: 1px solid var(--border-color); margin-top: 40px;
        }
        .category-header {
            display: flex; align-items: center; gap: 12px; padding: 16px 20px;
            background: var(--bg-secondary); border: 1px solid var(--border-color);
            border-radius: 8px; margin-bottom: 16px; border-left: 4px solid var(--accent);
        }
        .category-header h3 { flex: 1; font-size: 16px; font-weight: 600; color: var(--text-primary); margin: 0; }
        .category-count { color: var(--text-secondary); font-size: 13px; background: var(--bg-tertiary); padding: 4px 10px; border-radius: 12px; }
        .icon {
            width: 14px; height: 14px; border-radius: 50%; display: inline-block;
            background: radial-gradient(circle at 30% 30%, rgba(255,255,255,0.35), var(--accent-light));
            box-shadow: 0 0 8px rgba(46, 160, 67, 0.4);
        }
        /* ── New sections ── */
        .benign-note {
            background: #0d2b0d; border: 1px solid #238636; border-radius: 6px;
            padding: 10px 14px; margin-bottom: 12px; font-size: 13px; color: #56d364;
        }
        .benign-note strong { color: #3fb950; }
        .loaded-files-box {
            background: var(--bg-primary); border: 1px solid #30363d; border-radius: 6px;
            padding: 10px 14px; margin-bottom: 12px; font-size: 12px;
        }
        .loaded-files-box summary {
            cursor: pointer; color: var(--text-secondary); font-size: 12px;
            padding: 2px 0; user-select: none;
        }
        .loaded-files-box summary:hover { color: var(--accent-light); }
        .loaded-files-list { margin-top: 8px; }
        .loaded-files-list li {
            font-family: 'SF Mono','Fira Code',monospace;
            color: var(--text-primary); padding: 2px 0;
            word-break: break-all; list-style: none;
        }
        .loaded-files-list li::before { content: "→ "; color: var(--text-secondary); }
        #entry-table td, #entry-table th { font-size: 12px; }
        .section-nav { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 24px; }
        .section-nav a {
            padding: 6px 14px; background: var(--bg-tertiary); border: 1px solid var(--border-color);
            border-radius: 20px; color: var(--text-secondary); text-decoration: none; font-size: 13px;
        }
        .section-nav a:hover { border-color: var(--accent); color: var(--accent-light); }
        /* ── Chart section ── */
        .charts-outer { margin-bottom: 32px; }
        .charts-row-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 16px; }
        @media (max-width: 900px) { .charts-row-2 { grid-template-columns: 1fr; } }
        .chart-card {
            background: var(--bg-secondary); border: 1px solid var(--border-color);
            border-radius: 8px; padding: 16px; margin-bottom: 16px; position: relative;
        }
        .chart-title { font-size: 14px; font-weight: 600; color: var(--text-primary); margin-bottom: 4px; }
        .chart-sub { font-size: 12px; color: var(--text-secondary); margin-bottom: 12px; }
        .chart-canvas { display: block; width: 100%; cursor: crosshair; }
        .chart-tooltip {
            display: none; position: absolute; z-index: 999;
            background: #1f2428ee; border: 1px solid var(--border-color);
            border-radius: 6px; padding: 8px 12px; font-size: 12px;
            color: var(--text-primary); max-width: 320px;
            pointer-events: none; white-space: normal; line-height: 1.5;
        }
        .chart-tooltip hr { border-color: var(--border-color); margin: 4px 0; }
        .chart-tooltip code { font-size: 11px; }
        .dll-radial-wrap { display: flex; flex-wrap: wrap; gap: 16px; justify-content: center; }
        .dll-svg-wrap { display: flex; flex-direction: column; align-items: center; gap: 6px; }
        .dll-title { font-size: 12px; font-weight: 600; font-family: monospace; }
    </style>
</head>
<body>
    <header>
        <div class="header-content">
            <div class="logo">
                <div class="logo-text">KALI<span>HEKER</span></div>
                <div class="version">Prefetch Analyzer v1.0</div>
            </div>
            <div class="scan-info">
"#);

    // Info cards
    html.push_str(&format!(r#"
                <div class="info-card"><h3>Report Generated</h3><p>{}</p></div>
                <div class="info-card"><h3>Prefetch Entries</h3><div class="score">{}</div></div>
                <div class="info-card"><h3>Unique Executables</h3><div class="score">{}</div></div>
                <div class="info-card"><h3>Total Findings</h3><p>Critical: {} | High: {} | Medium: {} | Low: {}</p></div>
"#, 
        report.generated_at.format("%Y-%m-%d %H:%M:%S UTC"),
        report.total_entries,
        report.unique_executables,
        report.summary.critical,
        report.summary.high,
        report.summary.medium,
        report.summary.low
    ));

    html.push_str(r#"
            </div>
        </div>
    </header>

    <nav>
        <div class="nav-content">
            <div class="filter-buttons">
"#);

    html.push_str(&format!(r#"
                <button class="filter-btn active">All <span class="count">({})</span></button>
                <button class="filter-btn">Critical <span class="count">({})</span></button>
                <button class="filter-btn">High <span class="count">({})</span></button>
                <button class="filter-btn">Medium <span class="count">({})</span></button>
"#, 
        report.summary.total(),
        report.summary.critical,
        report.summary.high,
        report.summary.medium
    ));

    html.push_str(r#"
            </div>
            <div class="search-box">
                <input type="text" id="searchInput" placeholder="Search findings...">
            </div>
        </div>
    </nav>

    <main>
        <div class="stats-bar">
"#);

    html.push_str(&format!(r#"
            <div class="stat"><div class="stat-dot alert"></div> <span class="stat-label">Critical:</span> <span class="stat-value">{}</span></div>
            <div class="stat"><div class="stat-dot warning"></div> <span class="stat-label">High/Med:</span> <span class="stat-value">{}</span></div>
            <div class="stat"><div class="stat-dot notice"></div> <span class="stat-label">Low/Info:</span> <span class="stat-value">{}</span></div>
"#, 
        report.summary.critical,
        report.summary.high + report.summary.medium,
        report.summary.low + report.summary.info
    ));

    html.push_str(r##"
        </div>
        <div class="section-nav">
            <a href="#section-charts">📊 Analytics</a>
            <a href="#section-ts-coverage">🕒 Timestamp Coverage</a>
            <a href="#section-findings">🚨 Findings</a>
            <a href="#section-all-findings">📋 All Findings</a>
            <a href="#section-entry-table">🗂️ Prefetch Entries</a>
            <a href="#section-timestamps">⏱️ Timestamps</a>
            <a href="#section-timeline">📅 Timeline</a>
        </div>
"##);

    // ── Visual Analytics Charts ────────────────────────────────────────────
    html.push_str(&generate_charts_html(&report.raw_entries, &report.findings));
    html.push_str(&generate_timestamp_coverage_html(&report.raw_entries));

    // Critical & High Findings
    let critical_high: Vec<_> = report.findings.iter()
        .filter(|f| f.severity >= Severity::High)
        .collect();

    if !critical_high.is_empty() {
        html.push_str(r##"
        <div class="category-header" id="section-findings" style="border-left-color: var(--alert-bg);">
            <span class="icon"></span>
            <h3>🚨 Critical &amp; High Severity Findings</h3>
            <span class="category-count">"##);
        html.push_str(&format!("{} findings", critical_high.len()));
        html.push_str(r#"</span>
        </div>
"#);
        
        for finding in &critical_high {
            let severity_class = match finding.severity {
                Severity::Critical => "critical",
                Severity::High => "high",
                _ => "medium",
            };
            
            html.push_str(&format!(r#"
        <div class="finding-card {}">
            <div class="finding-header">
                <span class="severity-badge {}">{}</span>
                <span class="finding-title">{}</span>
            </div>
            <div class="finding-body">
                <div class="finding-description">{}</div>
"#, 
                severity_class,
                severity_class,
                finding.severity,
                finding.executable,
                finding.description
            ));
            
            // Benign installer annotation
            if finding.likely_benign_installer {
                html.push_str(r#"
                <div class="benign-note">
                    <strong>⚠️ Likely Benign — Installer Pattern Detected</strong><br>
                    This path matches the standard Microsoft Visual C++ Redistributable (VCREDIST / VC_REDIST)
                    self-extraction staging pattern: <code>\WINDOWS\TEMP\{GUID}\.CR\</code> or <code>\.BE\</code>.
                    These sub-directories are created transiently by the installer bootstrapper during package
                    staging and are almost certainly not an independent threat. Verify that the parent installer
                    was authorised before escalating.
                </div>
"#);
            }

            // Context / explanation block
            if let Some(ref ctx) = finding.context {
                html.push_str(&format!(r#"
                <div class="evidence-box" style="border-left: 3px solid #8b949e; margin-bottom:12px;">
                    <div class="evidence-line" style="color:var(--text-secondary);font-size:11px;margin-bottom:4px;">ANALYST CONTEXT</div>
                    <div style="font-family:inherit;font-size:13px;color:var(--text-primary);white-space:pre-wrap;word-break:break-word;">{}</div>
                </div>
"#, html_escape(ctx)));
            }

            // Evidence box with path
            if let Some(ref path) = finding.path {
                html.push_str(&format!(r#"
                <div class="evidence-box">
                    <div class="evidence-line"><span class="evidence-label">[full path]</span> {}</div>
                </div>
"#, html_escape(path)));
            }

            // Loaded files / DLLs evidence
            if !finding.loaded_files.is_empty() {
                html.push_str(&format!(r#"
                <div class="loaded-files-box">
                    <details>
                        <summary>📂 Non-system loaded files / DLLs ({} shown)</summary>
                        <ul class="loaded-files-list">
"#, finding.loaded_files.len()));
                for f in &finding.loaded_files {
                    html.push_str(&format!("                            <li>{}</li>\n", html_escape(f)));
                }
                html.push_str(r#"
                        </ul>
                    </details>
                </div>
"#);
            }
            
            // Metadata tags
            html.push_str(r#"<div class="metadata-tags">"#);
            html.push_str(&format!(r#"<div class="meta-tag">Category: <strong>{}</strong></div>"#, finding.category));
            
            if let Some(ref mitre) = finding.mitre_attack {
                html.push_str(&format!(
                    r#"<div class="meta-tag">MITRE: <a class="mitre-link" href="https://attack.mitre.org/techniques/{}" target="_blank"><strong>{}</strong></a></div>"#,
                    mitre.replace('.', "/"),
                    mitre
                ));
            }
            
            if finding.run_count > 0 {
                html.push_str(&format!(r#"<div class="meta-tag">Run Count: <strong>{}</strong></div>"#, finding.run_count));
            }

            if let Some(last) = finding.last_run {
                html.push_str(&format!(
                    r#"<div class="meta-tag">Last Run: <strong>{}</strong></div>"#,
                    last.format("%Y-%m-%d %H:%M:%S")
                ));
            }

            if let Some(entry) = entry_by_filename.get(finding.source_file.as_str()) {
                html.push_str(&format!(r#"<div class="meta-tag">Source Created: <strong>{}</strong></div>"#, html_escape(&entry.source_created)));
                html.push_str(&format!(r#"<div class="meta-tag">Source Modified: <strong>{}</strong></div>"#, html_escape(&entry.source_modified)));
                html.push_str(&format!(r#"<div class="meta-tag">Source Accessed: <strong>{}</strong></div>"#, html_escape(&entry.source_accessed)));
            }
            
            html.push_str(r#"</div>
            </div>
        </div>
"#);
        }
    }

    // ── Findings with Analyst Context (Medium / Low with context, benign notes, loaded files) ──
    let notable_with_context: Vec<_> = report.findings.iter()
        .filter(|f| f.severity < Severity::High)
        .filter(|f| f.context.is_some() || !f.loaded_files.is_empty() || f.likely_benign_installer)
        .collect();

    if !notable_with_context.is_empty() {
        html.push_str(r#"
        <div class="category-header" style="border-left-color: #d29922;">
            <span class="icon"></span>
            <h3>🔎 Analyst Context — Medium / Low Findings</h3>
            <span class="category-count">"#);
        html.push_str(&format!("{} findings with context", notable_with_context.len()));
        html.push_str(r#"</span>
        </div>
"#);

        for finding in &notable_with_context {
            let severity_class = match finding.severity {
                Severity::Medium => "medium",
                Severity::Low => "low",
                _ => "info",
            };

            html.push_str(&format!(r#"
        <div class="finding-card {}">
            <div class="finding-header">
                <span class="severity-badge {}">{}</span>
                <span class="finding-title">{}</span>
            </div>
            <div class="finding-body">
                <div class="finding-description">{}</div>
"#,
                severity_class,
                severity_class,
                finding.severity,
                html_escape(&finding.executable),
                html_escape(&finding.description)
            ));

            // Benign installer annotation
            if finding.likely_benign_installer {
                html.push_str(r#"
                <div class="benign-note">
                    <strong>⚠️ Likely Benign — Installer Pattern Detected</strong><br>
                    This path matches the standard Microsoft Visual C++ Redistributable (VCREDIST / VC_REDIST)
                    self-extraction staging pattern: <code>\WINDOWS\TEMP\{GUID}\.CR\</code> or <code>\.BE\</code>.
                    These sub-directories are created transiently by the installer bootstrapper during package
                    staging and are almost certainly not an independent threat. Verify that the parent installer
                    was authorised before escalating.
                </div>
"#);
            }

            // Context / explanation block
            if let Some(ref ctx) = finding.context {
                html.push_str(&format!(r#"
                <div class="evidence-box" style="border-left: 3px solid #8b949e; margin-bottom:12px;">
                    <div class="evidence-line" style="color:var(--text-secondary);font-size:11px;margin-bottom:4px;">ANALYST CONTEXT</div>
                    <div style="font-family:inherit;font-size:13px;color:var(--text-primary);white-space:pre-wrap;word-break:break-word;">{}</div>
                </div>
"#, html_escape(ctx)));
            }

            // Evidence box with path
            if let Some(ref path) = finding.path {
                html.push_str(&format!(r#"
                <div class="evidence-box">
                    <div class="evidence-line"><span class="evidence-label">[full path]</span> {}</div>
                </div>
"#, html_escape(path)));
            }

            // Loaded files / DLLs evidence
            if !finding.loaded_files.is_empty() {
                html.push_str(&format!(r#"
                <div class="loaded-files-box">
                    <details>
                        <summary>📂 Non-system loaded files / DLLs ({} shown)</summary>
                        <ul class="loaded-files-list">
"#, finding.loaded_files.len()));
                for f in &finding.loaded_files {
                    html.push_str(&format!("                            <li>{}</li>\n", html_escape(f)));
                }
                html.push_str(r#"
                        </ul>
                    </details>
                </div>
"#);
            }

            // Metadata tags
            html.push_str(r#"<div class="metadata-tags">"#);
            html.push_str(&format!(r#"<div class="meta-tag">Category: <strong>{}</strong></div>"#,
                html_escape(&finding.category.to_string())));
            if let Some(ref mitre) = finding.mitre_attack {
                html.push_str(&format!(
                    r#"<div class="meta-tag">MITRE: <a class="mitre-link" href="https://attack.mitre.org/techniques/{}" target="_blank"><strong>{}</strong></a></div>"#,
                    mitre.replace('.', "/"), mitre));
            }
            if finding.run_count > 0 {
                html.push_str(&format!(r#"<div class="meta-tag">Run Count: <strong>{}</strong></div>"#, finding.run_count));
            }

            if let Some(last) = finding.last_run {
                html.push_str(&format!(
                    r#"<div class="meta-tag">Last Run: <strong>{}</strong></div>"#,
                    last.format("%Y-%m-%d %H:%M:%S")
                ));
            }

            if let Some(entry) = entry_by_filename.get(finding.source_file.as_str()) {
                html.push_str(&format!(r#"<div class="meta-tag">Source Created: <strong>{}</strong></div>"#, html_escape(&entry.source_created)));
                html.push_str(&format!(r#"<div class="meta-tag">Source Modified: <strong>{}</strong></div>"#, html_escape(&entry.source_modified)));
                html.push_str(&format!(r#"<div class="meta-tag">Source Accessed: <strong>{}</strong></div>"#, html_escape(&entry.source_accessed)));
            }
            html.push_str(r#"</div>
            </div>
        </div>
"#);
        }
    }

    // All Findings Table
    html.push_str(r##"
        <div class="category-header" id="section-all-findings">
            <span class="icon"></span>
            <h3>📋 All Findings</h3>
            <span class="category-count">"##);
    html.push_str(&format!("{} total", report.findings.len()));
    html.push_str(r#"</span>
        </div>
        
        <div style="background: var(--bg-secondary); border: 1px solid var(--border-color); border-radius: 8px; overflow: hidden;">
            <table>
                <thead>
                    <tr>
                        <th>Severity</th>
                        <th>Executable</th>
                        <th>Category</th>
                        <th>Last Run</th>
                        <th>Source Accessed</th>
                        <th>Description</th>
                        <th>MITRE ATT&CK</th>
                    </tr>
                </thead>
                <tbody>
"#);

    for finding in &report.findings {
        let severity_class = match finding.severity {
            Severity::Critical => "critical",
            Severity::High => "high",
            Severity::Medium => "medium",
            Severity::Low => "low",
            Severity::Info => "info",
        };
        
        html.push_str(&format!(r#"
                    <tr>
                        <td><span class="severity-badge {}">{}</span></td>
                        <td><code>{}</code></td>
                        <td>{}</td>
                        <td>{}</td>
                        <td>{}</td>
                        <td>{}</td>
                        <td>{}</td>
                    </tr>
"#,
            severity_class,
            finding.severity,
            finding.executable,
            finding.category,
            finding
                .last_run
                .map(|t| t.format("%Y-%m-%d %H:%M:%S").to_string())
                .unwrap_or_else(|| "-".to_string()),
            entry_by_filename
                .get(finding.source_file.as_str())
                .map(|e| html_escape(&e.source_accessed))
                .unwrap_or_else(|| "-".to_string()),
            truncate(&finding.description, 60),
            finding.mitre_attack.as_ref().map(|m| 
                format!(r#"<a class="mitre-link" href="https://attack.mitre.org/techniques/{}" target="_blank">{}</a>"#, 
                    m.replace('.', "/"), m)
            ).unwrap_or_else(|| "-".to_string())
        ));
    }

    html.push_str(r#"
                </tbody>
            </table>
        </div>
"#);

    // ── New enriched sections ──────────────────────────────────────────────
    html.push_str(&generate_complete_entry_table_html(&report.raw_entries));
    html.push_str(&generate_timestamps_html(&report.raw_entries));
    html.push_str(&generate_timeline_html(&report.raw_entries));

    // Footer and JavaScript
    html.push_str(r#"
    </main>
    
    <footer>
        <p>Generated by <strong>KaliHeker Prefetch Analyzer</strong></p>
        <p>A forensic analysis tool for Windows Prefetch data</p>
    </footer>

    <script>
        // Filter functionality
        let currentFilter = 'all';
        
        document.querySelectorAll('.filter-btn').forEach(btn => {
            btn.addEventListener('click', function() {
                // Update active state
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                this.classList.add('active');
                
                // Get filter type from button text
                const filterText = this.textContent.trim().toLowerCase();
                if (filterText.startsWith('all')) currentFilter = 'all';
                else if (filterText.startsWith('critical')) currentFilter = 'critical';
                else if (filterText.startsWith('high')) currentFilter = 'high';
                else if (filterText.startsWith('medium')) currentFilter = 'medium';
                else if (filterText.startsWith('low')) currentFilter = 'low';
                
                applyFilters();
            });
        });
        
        function applyFilters() {
            // Filter finding cards
            document.querySelectorAll('.finding-card').forEach(card => {
                const level = card.classList.contains('critical') ? 'critical' :
                             card.classList.contains('high') ? 'high' :
                             card.classList.contains('medium') ? 'medium' :
                             card.classList.contains('low') ? 'low' : 'info';
                
                if (currentFilter === 'all' || level === currentFilter) {
                    card.style.display = '';
                } else {
                    card.style.display = 'none';
                }
            });
            
            // Filter table rows
            document.querySelectorAll('tbody tr').forEach(row => {
                const badge = row.querySelector('.severity-badge');
                if (!badge) return;
                
                const level = badge.classList.contains('critical') ? 'critical' :
                             badge.classList.contains('high') ? 'high' :
                             badge.classList.contains('medium') ? 'medium' :
                             badge.classList.contains('low') ? 'low' : 'info';
                
                if (currentFilter === 'all' || level === currentFilter) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
            
            updateVisibleCount();
        }
        
        function updateVisibleCount() {
            const visibleCards = document.querySelectorAll('.finding-card:not([style*="display: none"])').length;
            const visibleRows = document.querySelectorAll('tbody tr:not([style*="display: none"])').length;
            
            // Update category counts if elements exist
            const categoryHeaders = document.querySelectorAll('.category-header');
            categoryHeaders.forEach(header => {
                const countSpan = header.querySelector('.category-count');
                if (countSpan && header.querySelector('h3').textContent.includes('All Findings')) {
                    countSpan.textContent = visibleRows + ' visible';
                }
            });
        }
        
        // Search functionality (if search box exists)
        const searchInput = document.getElementById('searchInput');
        if (searchInput) {
            searchInput.addEventListener('input', function() {
                const query = this.value.toLowerCase();
                
                document.querySelectorAll('.finding-card').forEach(card => {
                    const text = card.textContent.toLowerCase();
                    if (text.includes(query)) {
                        card.style.display = '';
                    } else {
                        card.style.display = 'none';
                    }
                });
                
                document.querySelectorAll('tbody tr').forEach(row => {
                    const text = row.textContent.toLowerCase();
                    if (text.includes(query)) {
                        row.style.display = '';
                    } else {
                        row.style.display = 'none';
                    }
                });
            });
        }
        
        // Collapsible sections
        document.querySelectorAll('.category-header').forEach(header => {
            header.style.cursor = 'pointer';
            header.addEventListener('click', function() {
                const nextSibling = this.nextElementSibling;
                if (nextSibling && (nextSibling.tagName === 'DIV' || nextSibling.classList.contains('finding-card'))) {
                    // Toggle visibility of all following finding cards until next header
                    let sibling = this.nextElementSibling;
                    while (sibling && !sibling.classList.contains('category-header')) {
                        if (sibling.style.display === 'none') {
                            sibling.style.display = '';
                        } else {
                            sibling.style.display = 'none';
                        }
                        sibling = sibling.nextElementSibling;
                    }
                }
            });
        });
    </script>
</body>
</html>
"#);

    html
}

/// Save report to file
pub fn save_report<P: AsRef<Path>>(path: P, content: &str) -> Result<()> {
    fs::write(path, content)?;
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
//  Visual Analytics Charts
// ─────────────────────────────────────────────────────────────────────────────

/// Build the full charts section: HTML containers + embedded JSON data +
/// pure-SVG/Canvas JavaScript renderers (no external dependencies).
pub fn generate_charts_html(entries: &[PrefetchEntry], findings: &[crate::models::Finding]) -> String {
    use crate::models::Severity;
    use std::collections::HashMap;

    let sev_num = |s: &Severity| -> u8 {
        match s {
            Severity::Critical => 5,
            Severity::High => 4,
            Severity::Medium => 3,
            Severity::Low => 2,
            Severity::Info => 1,
        }
    };

    let mut exe_sev: HashMap<String, u8> = HashMap::new();
    for f in findings {
        let n = sev_num(&f.severity);
        let e = exe_sev.entry(f.executable.to_uppercase()).or_insert(0);
        if n > *e {
            *e = n;
        }
    }

    let mut single = 0u64;
    let mut low = 0u64;
    let mut medium = 0u64;
    let mut high = 0u64;
    for e in entries {
        match e.run_count() {
            1 => single += 1,
            2..=5 => low += 1,
            6..=10 => medium += 1,
            _ => high += 1,
        }
    }

    let histogram = serde_json::json!([
        {"bucket":"1 run","count":single},
        {"bucket":"2-5 runs","count":low},
        {"bucket":"6-10 runs","count":medium},
        {"bucket":"11+ runs","count":high}
    ]);

    let mut timeline: Vec<serde_json::Value> = Vec::new();
    for e in entries {
        let s = *exe_sev.get(&e.executable_name.to_uppercase()).unwrap_or(&0);
        for ts in e.get_run_times() {
            timeline.push(serde_json::json!({
                "t": ts.and_utc().timestamp_millis(),
                "label": ts.format("%Y-%m-%d %H:%M:%S").to_string(),
                "exe": e.executable_name,
                "sev": s,
            }));
        }
    }
    timeline.sort_by_key(|v| v["t"].as_i64().unwrap_or(0));

    let mut by_path: HashMap<String, (u64, u8)> = HashMap::new();
    for e in entries {
        let path = e
            .get_executable_path()
            .unwrap_or_else(|| format!("\\UNKNOWN\\{}", e.executable_name));
        let sev = *exe_sev.get(&e.executable_name.to_uppercase()).unwrap_or(&0);
        let slot = by_path.entry(path).or_insert((0, 0));
        slot.0 += e.run_count() as u64;
        if sev > slot.1 {
            slot.1 = sev;
        }
    }

    let mut top_paths: Vec<serde_json::Value> = by_path
        .into_iter()
        .map(|(path, (runs, sev))| serde_json::json!({"path": path, "runs": runs, "sev": sev}))
        .collect();
    top_paths.sort_by(|a, b| b["runs"].as_u64().cmp(&a["runs"].as_u64()));
    top_paths.truncate(12);

    let chart_data = serde_json::json!({
        "histogram": histogram,
        "timeline": timeline,
        "topPaths": top_paths,
    });

    let chart_json = serde_json::to_string(&chart_data).unwrap_or_else(|_| "{}".to_string());

    let mut html = String::new();
    html.push_str(
        r#"
        <div class="category-header" id="section-charts" style="border-left-color: #58a6ff;">
            <span class="icon"></span>
            <h3>📊 Visual Analytics (D3.js)</h3>
            <span class="category-count">3 D3 charts</span>
        </div>
        <div class="charts-outer">
            <div class="charts-row-2">
                <div class="chart-card">
                    <div class="chart-title">Run Count Distribution</div>
                    <div class="chart-sub">Executables grouped by execution frequency</div>
                    <div id="d3-hist"></div>
                </div>
                <div class="chart-card">
                    <div class="chart-title">Top Execution Paths</div>
                    <div class="chart-sub">Most active execution paths by run count</div>
                    <div id="d3-paths"></div>
                </div>
            </div>
            <div class="chart-card">
                <div class="chart-title">Execution Timeline</div>
                <div class="chart-sub">Time-distributed execution points colored by severity</div>
                <div id="d3-timeline"></div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
        <script>
        (function() {
            const data = "#,
    );
    html.push_str(&chart_json);
    html.push_str(
        r#";
            if (!window.d3) { return; }

            const sevColor = (s) => ({1:'#58a6ff',2:'#56d364',3:'#d29922',4:'#fd8c00',5:'#da3633'}[s] || '#8b949e');

            function makeSvg(container, w, h) {
                d3.select(container).html('');
                return d3.select(container).append('svg').attr('width', w).attr('height', h);
            }

            (function renderHistogram() {
                const w = 520, h = 280, m = {t:20,r:16,b:50,l:52};
                const svg = makeSvg('#d3-hist', w, h);
                const x = d3.scaleBand().domain(data.histogram.map(d => d.bucket)).range([m.l, w - m.r]).padding(0.2);
                const y = d3.scaleLinear().domain([0, d3.max(data.histogram, d => d.count) || 1]).nice().range([h - m.b, m.t]);

                svg.append('g').attr('transform', `translate(0,${h - m.b})`).call(d3.axisBottom(x));
                svg.append('g').attr('transform', `translate(${m.l},0)`).call(d3.axisLeft(y).ticks(5));

                svg.selectAll('rect.bar')
                    .data(data.histogram)
                    .enter()
                    .append('rect')
                    .attr('class', 'bar')
                    .attr('x', d => x(d.bucket))
                    .attr('y', d => y(d.count))
                    .attr('width', x.bandwidth())
                    .attr('height', d => y(0) - y(d.count))
                    .attr('fill', '#2ea043');

                svg.selectAll('text.val')
                    .data(data.histogram)
                    .enter()
                    .append('text')
                    .attr('x', d => x(d.bucket) + x.bandwidth()/2)
                    .attr('y', d => y(d.count) - 6)
                    .attr('text-anchor', 'middle')
                    .attr('fill', '#c9d1d9')
                    .attr('font-size', 12)
                    .text(d => d.count);
            })();

            (function renderTopPaths() {
                const w = 520, h = 320, m = {t:20,r:16,b:24,l:220};
                const top = data.topPaths.slice(0, 10).reverse();
                const svg = makeSvg('#d3-paths', w, h);
                const x = d3.scaleLinear().domain([0, d3.max(top, d => d.runs) || 1]).nice().range([m.l, w - m.r]);
                const y = d3.scaleBand().domain(top.map(d => d.path)).range([h - m.b, m.t]).padding(0.18);

                svg.append('g').attr('transform', `translate(0,${h - m.b})`).call(d3.axisBottom(x).ticks(5));
                svg.append('g').attr('transform', `translate(${m.l},0)`).call(d3.axisLeft(y).tickFormat(v => v.length > 34 ? v.slice(0,34) + '...' : v));

                svg.selectAll('rect.path')
                    .data(top)
                    .enter()
                    .append('rect')
                    .attr('x', m.l)
                    .attr('y', d => y(d.path))
                    .attr('width', d => x(d.runs) - m.l)
                    .attr('height', y.bandwidth())
                    .attr('fill', d => sevColor(d.sev));
            })();

            (function renderTimeline() {
                const events = data.timeline;
                const w = 1060, h = 320, m = {t:20,r:16,b:50,l:60};
                const svg = makeSvg('#d3-timeline', w, h);
                if (!events.length) {
                    svg.append('text').attr('x', w/2).attr('y', h/2).attr('text-anchor', 'middle').attr('fill', '#8b949e').text('No timeline data');
                    return;
                }
                const x = d3.scaleTime()
                    .domain(d3.extent(events, d => new Date(d.t)))
                    .range([m.l, w - m.r]);
                const y = d3.scaleLinear()
                    .domain([1, 5])
                    .range([h - m.b, m.t]);

                svg.append('g').attr('transform', `translate(0,${h - m.b})`).call(d3.axisBottom(x));
                svg.append('g').attr('transform', `translate(${m.l},0)`).call(d3.axisLeft(y).ticks(5).tickFormat(d => ['','Info','Low','Med','High','Crit'][d] || ''));

                svg.selectAll('circle.ev')
                    .data(events)
                    .enter()
                    .append('circle')
                    .attr('cx', d => x(new Date(d.t)))
                    .attr('cy', d => y(d.sev || 1))
                    .attr('r', 4)
                    .attr('fill', d => sevColor(d.sev))
                    .append('title')
                    .text(d => `${d.label} | ${d.exe}`);
            })();
        })();
        </script>
"#,
    );

    html
}
pub fn generate_complete_entry_table_html(entries: &[PrefetchEntry]) -> String {
    let mut html = String::new();

    html.push_str(r#"
        <div class="category-header" id="section-entry-table" style="border-left-color: #58a6ff;">
            <span class="icon"></span>
            <h3>🗂️ Complete Prefetch Entry Table</h3>
"#);
    html.push_str(&format!(
        r#"<span class="category-count">{} entries</span></div>
"#,
        entries.len()
    ));

    // Sort entries by last execution time (most recent first)
    let mut sorted: Vec<&PrefetchEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| b.last_run().cmp(&a.last_run()));

    html.push_str(r#"
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table id="entry-table">
            <thead>
                <tr>
                    <th>Prefetch File</th>
                    <th>Hash</th>
                    <th>Executable</th>
                    <th>Source Created</th>
                    <th>Source Modified</th>
                    <th>Source Accessed</th>
                    <th>Volume0 Created</th>
                    <th>Run Count</th>
                    <th>First Run</th>
                    <th>Last Run</th>
                    <th>Files Loaded</th>
                    <th>Execution Path</th>
                </tr>
            </thead>
            <tbody>
"#);

    for entry in &sorted {
        let hash = entry.extract_prefetch_hash().unwrap_or_else(|| "?".to_string());
        let pf_base = std::path::Path::new(&entry.filename)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(&entry.filename);
        let first = entry.first_run()
            .map(|t| t.format("%Y-%m-%d %H:%M:%S").to_string())
            .unwrap_or_else(|| "-".to_string());
        let last = entry.last_run()
            .map(|t| t.format("%Y-%m-%d %H:%M:%S").to_string())
            .unwrap_or_else(|| "-".to_string());
        let exe_path = entry
            .get_executable_path()
            .unwrap_or_else(|| "-".to_string());

        html.push_str(&format!(
            r#"
                <tr>
                    <td><code style="font-size:11px;">{}</code></td>
                    <td><code style="color:#58a6ff;">{}</code></td>
                    <td><code>{}</code></td>
                    <td style="font-size:12px;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="text-align:center;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="font-size:12px;">{}</td>
                    <td style="text-align:center;">{}</td>
                    <td style="font-size:11px;word-break:break-all;">{}</td>
                </tr>
"#,
            html_escape(pf_base),
            html_escape(&hash),
            html_escape(&entry.executable_name),
            html_escape(&entry.source_created),
            html_escape(&entry.source_modified),
            html_escape(&entry.source_accessed),
            html_escape(&entry.volume0_created),
            entry.run_count(),
            html_escape(&first),
            html_escape(&last),
            entry
                .files_loaded
                .split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .count(),
            html_escape(&exe_path),
        ));
    }

    html.push_str(r#"
            </tbody>
        </table>
        </div>
"#);

    html
}

/// Renders the **Execution Timestamps** section — every recorded timestamp
/// for every prefetch entry, grouped by executable, sorted newest-first.
pub fn generate_timestamps_html(entries: &[PrefetchEntry]) -> String {
    let mut html = String::new();

    // Sort entries by last run (most recent activity first)
    let mut sorted: Vec<&PrefetchEntry> = entries.iter().collect();
    sorted.sort_by(|a, b| b.last_run().cmp(&a.last_run()));

    html.push_str(&format!(r#"
        <div class="category-header" id="section-timestamps" style="border-left-color: #d29922;">
            <span class="icon"></span>
            <h3>⏱️ Execution Timestamps (All Entries)</h3>
            <span class="category-count">{} executables</span>
        </div>
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table>
            <thead>
                <tr>
                    <th>Executable</th>
                    <th>Prefetch Hash</th>
                    <th>Run #</th>
                    <th>Timestamp</th>
                </tr>
            </thead>
            <tbody>
"#, sorted.len()));

    for entry in &sorted {
        let hash = entry.extract_prefetch_hash().unwrap_or_else(|| "?".to_string());
        let mut times = entry.get_run_times();
        times.sort_by(|a, b| b.cmp(a)); // newest first

        for (run_idx, ts) in times.iter().enumerate() {
            html.push_str(&format!(
                r#"
                <tr>
                    <td><code>{}</code></td>
                    <td><code style="color:#58a6ff;">{}</code></td>
                    <td style="text-align:center;color:var(--text-secondary);">Run {}</td>
                    <td style="font-family:'SF Mono','Fira Code',monospace;font-size:13px;">{}</td>
                </tr>
"#,
                html_escape(&entry.executable_name),
                html_escape(&hash),
                run_idx + 1,
                ts.format("%Y-%m-%d %H:%M:%S%.3f"),
            ));
        }
    }

    html.push_str(r#"
            </tbody>
        </table>
        </div>
"#);

    html
}

/// Renders the **Full Executable Timeline** — every execution event from every
/// prefetch entry in strict chronological order (oldest → newest), with the
/// originating executable and prefetch hash annotated per row.
pub fn generate_timeline_html(entries: &[PrefetchEntry]) -> String {
    // Collect (timestamp, executable_name, hash) tuples
    let mut events: Vec<(chrono::NaiveDateTime, String, String)> = Vec::new();

    for entry in entries {
        let hash = entry.extract_prefetch_hash().unwrap_or_else(|| "?".to_string());
        for ts in entry.get_run_times() {
            events.push((ts, entry.executable_name.clone(), hash.clone()));
        }
    }

    // Sort chronologically
    events.sort_by_key(|(ts, _, _)| *ts);

    let mut html = String::new();

    html.push_str(&format!(r#"
        <div class="category-header" id="section-timeline" style="border-left-color: #3fb950;">
            <span class="icon"></span>
            <h3>📅 Full Executable Timeline</h3>
            <span class="category-count">{} execution events</span>
        </div>
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Timestamp</th>
                    <th>Executable</th>
                    <th>Prefetch Hash</th>
                </tr>
            </thead>
            <tbody>
"#, events.len()));

    for (i, (ts, exe, hash)) in events.iter().enumerate() {
        html.push_str(&format!(
            r#"
                <tr>
                    <td style="text-align:center;color:var(--text-secondary);font-size:12px;">{}</td>
                    <td style="font-family:'SF Mono','Fira Code',monospace;font-size:13px;">{}</td>
                    <td><code>{}</code></td>
                    <td><code style="color:#58a6ff;">{}</code></td>
                </tr>
"#,
            i + 1,
            ts.format("%Y-%m-%d %H:%M:%S%.3f"),
            html_escape(exe),
            html_escape(hash),
        ));
    }

    html.push_str(r#"
            </tbody>
        </table>
        </div>
"#);

    html
}

/// Minimal HTML entity escaping to prevent XSS in report output.
fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn truncate(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        s.to_string()
    } else {
        format!("{}...", &s[..max_len-3])
    }
}

fn generate_timestamp_coverage_html(entries: &[PrefetchEntry]) -> String {
    let mut html = String::new();

    let mut source_created = 0usize;
    let mut source_modified = 0usize;
    let mut source_accessed = 0usize;
    let mut volume_created = 0usize;
    let mut last_run = 0usize;

    for e in entries {
        if !e.source_created.trim().is_empty() {
            source_created += 1;
        }
        if !e.source_modified.trim().is_empty() {
            source_modified += 1;
        }
        if !e.source_accessed.trim().is_empty() {
            source_accessed += 1;
        }
        if !e.volume0_created.trim().is_empty() {
            volume_created += 1;
        }
        if !e.last_run_raw.trim().is_empty() {
            last_run += 1;
        }
    }

    html.push_str(&format!(r#"
        <div class="category-header" id="section-ts-coverage" style="border-left-color: #1f6feb;">
            <span class="icon"></span>
            <h3>🕒 Timestamp Coverage</h3>
            <span class="category-count">{} entries evaluated</span>
        </div>
        <div style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:8px;overflow:hidden;margin-bottom:24px;">
        <table>
            <thead>
                <tr>
                    <th>Timestamp Field</th>
                    <th>Present Count</th>
                    <th>Coverage</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>SourceCreated</td><td>{}</td><td>{:.2}%</td></tr>
                <tr><td>SourceModified</td><td>{}</td><td>{:.2}%</td></tr>
                <tr><td>SourceAccessed</td><td>{}</td><td>{:.2}%</td></tr>
                <tr><td>Volume0Created</td><td>{}</td><td>{:.2}%</td></tr>
                <tr><td>LastRun</td><td>{}</td><td>{:.2}%</td></tr>
            </tbody>
        </table>
        </div>
"#,
        entries.len(),
        source_created,
        percentage(source_created, entries.len()),
        source_modified,
        percentage(source_modified, entries.len()),
        source_accessed,
        percentage(source_accessed, entries.len()),
        volume_created,
        percentage(volume_created, entries.len()),
        last_run,
        percentage(last_run, entries.len()),
    ));

    html
}

fn percentage(n: usize, total: usize) -> f64 {
    if total == 0 {
        0.0
    } else {
        (n as f64 / total as f64) * 100.0
    }
}
